### ISSUE TITLE
Can't iterate over selected layers with selectedLayers

### ISSUE THREAD

**Issue by plrthink** [BohemianCoding/SketchAPI#10]
I follow the guide on this [page](http://developer.sketchapp.com/reference/api/), however the code below doesn't work

``` js
var sketch = context.api()
var document = sketch.selectedDocument
var selection = document.selectedLayers
selection.iterate( function (item) { log( item.name() ) } )
```

It would throw this error:

```
TypeError: undefined is not an object (evaluating 'this._object._application.wrapObject')
line: 1627
sourceURL: /Applications/Sketch.app/Contents/Resources/SketchAPI.js
column: 54
```

But this works as expected：

``` js
var selection = context.selection

for (var i = 0; i < selection.length; i++) {
  var _selection = selection[i]
  log(_selection.name())
}
```

And here is my env:

``` js
log(sketch.api_version) // 1.1
log(sketch.version) // 40.2
log(sketch.build) // 33826
```

**Comment by plrthink** [comment]
Also I'm new to Sketch plugin development, the docs on the https://developer.sketch.com really confuses me. Some parts says we should use cocoascript but the API section marks cocoascript version as *deprecated*. 

I have learned that this pure JS version is WIP, so does it mean we should still using cocoscript nowadays?

**Comment by kgn** [comment]
I'm also running into this with the following code:

``` javascript
var sketch = context.api()
var document = sketch.selectedDocument;
var selection = document.selectedLayers;

if (selection.isEmpty) {
    sketch.message("Nothing selected; nothing to export");
} else {
    selection.iterate(function(item) {
        log(item.name);
    });
}
```

```
TypeError: undefined is not an object (evaluating 'this._object._application.wrapObject')
line: 1627
sourceURL: /Applications/Sketch.app/Contents/Resources/SketchAPI.js
column: 54


Script executed in 0.025134s
```

**Comment by kgn** [comment]
This has been fixed in the `develop` branch

**Comment by mattpfeffer** [comment]
I was scratching my head over this one while trying to iterate over child layers on a page, should have just checked the issue log.

**Comment by emilwidlund** [comment]
When does this fix reach the retail Sketch App?

**Comment by plrthink** [comment]
I just tried the code in Sketch 41, it works except that `name` is not function, it's a property on layer object.

will close this.
