### ISSUE TITLE
create Shape with style not work

### ISSUE THREAD

**Issue by nichenqin** [BohemianCoding/SketchAPI#105]
<img width="1429" alt="wx20180303-142800 2x" src="https://user-images.githubusercontent.com/22788984/36931385-2a72776c-1eef-11e8-8ffe-5e895d3133aa.png">
I can log the style property from selected layer which works as intended according to the source code, but the color just not rendered on the layer

**Comment by mathieudutour** [comment]
actually, I think any shape created by the API doesn't work. It's missing a path.

**Comment by mathieudutour** [comment]
fixed in https://github.com/BohemianCoding/SketchAPI/commit/fcb25f2a17b1673a121a87784f24ef75bfb54bad
