### ISSUE TITLE
can Artboard create flow prototype?

### ISSUE THREAD

**Issue by nichenqin** [BohemianCoding/SketchAPI#106]
I can create an artboard by `new Artboard({ flow: { target: anothorArtboard } })` and there will be a link between two artboards, but when I click preview it does not work.
And I find that I can not create link in sketch(from an artboard).
Did I miss something or the `flow` property should be removed from document(in Artboard)?

**Comment by mathieudutour** [comment]
oh it only from a layer to an artboard, not from an artboard to an artboard. I'll remove it

**Comment by mathieudutour** [comment]
fixed in https://github.com/BohemianCoding/SketchAPI/commit/96be5efc7e7958f8b76e5df1846f304cd3ecf2ff
