### ISSUE TITLE
Group Class doesn't implement isGroup

### ISSUE THREAD

**Issue by tylergaw** [BohemianCoding/SketchAPI#11]
@samdeane Guessing you may already have this well underway in a branch somewhere, but just hit this working with the JS API and wanted to documented it.

**Issue:**
Checking for `object.isGroup` on a known `Group` always returns `false`.

**Expected:**
Checking for `object.isGroup` on a known `Group` should return `true`.

Poked at the source and saw that in the `Group` class it's `is_group` and not `isGroup` https://github.com/BohemianCoding/SketchAPI/blob/master/Source/Group.js#L17

Wondering if that can be updated to `isGroup` to override the default https://github.com/BohemianCoding/SketchAPI/blob/master/Source/Layer.js#L43

**Comment by kgn** [comment]
This looks to be fixed in the `develop` branch: https://github.com/BohemianCoding/SketchAPI/blob/develop/Source/Group.js#L40

**Comment by samdeane** [comment]
Yeah, it's fixed in an upcoming release..

**Comment by tylergaw** [comment]
👍  Noticed this is working as expected in Sketch 41. Going to close this. Thanks ya'll
