### ISSUE TITLE
adjustToFit method not work for Artboard

### ISSUE THREAD

**Issue by nichenqin** [BohemianCoding/SketchAPI#111]
It looks like the methods inherits from `Group`, but it just not works.
I find it works by following script
```javascipt
document.sketchObject.actionsController().actionForID("MSResizeArtboardToFitAction").resizeArtboardToFit(nil)
```
but should ensure the `artboard` layer is selected..

Did I miss something or is this a bug? Thanks!

**Comment by mathieudutour** [comment]
It is indeed a bug, will look into it
