### ISSUE TITLE
methods missed in Settings API

### ISSUE THREAD

**Issue by nichenqin** [BohemianCoding/SketchAPI#116]
![image](https://user-images.githubusercontent.com/22788984/37076911-7948c9e6-2213-11e8-9c09-84c9781b2475.png)
It looks like not every method imported from Settings API.

another question, how do I set `SketchAPILocation` back to default?
![image](https://user-images.githubusercontent.com/22788984/37076978-c5867f42-2213-11e8-9a9c-862b61638c23.png)

Thx!

**Comment by mathieudutour** [comment]
To remove the SketchAPILocation, run `defaults delete com.bohemiancoding.sketch3 SketchAPILocation`

I'll look into why `layerSettingForKey` and such are missing 🤔

**Comment by mathieudutour** [comment]
Will be fixed in 49.1
