### ISSUE TITLE
Shared layer/text styles support

### ISSUE THREAD

**Issue by lucaorio** [BohemianCoding/SketchAPI#118]
Is there any way to access/manipulate layer and text styles? Is it just missing in the documentation, or it's something that'll be provided in the future?

**Comment by mathieudutour** [comment]
The support for styles is not great in this first version. The only type of layer that has some information is the `ShapeGroup`: http://developer.sketchapp.com/reference/api/#style

I'm working on adding those information (and shadows/innerShadows/gradient) to all the others

**Comment by lucaorio** [comment]
Hey @mathieudutour, that's great! I explained myself badly, though. I was referring to the shared styles !:)
