### ISSUE TITLE
inconsistent property definition

### ISSUE THREAD

**Issue by robintindale** [BohemianCoding/SketchAPI#122]
This caught me out when browsing the new docs http://developer.sketchapp.com/reference/api/

Sometimes read-only properties are in the properties table at the top of the object, sometimes they're separate in the body. In the old docs, the difference between properties and methods was very clear, but in this new format, the lines are blurred

An example here is `Document`. The `pages` property is hidden in the object body, and not shown in the properties table. Whereas for `Group`, the `layers` property is in the properties table

**Comment by mathieudutour** [comment]
The `pages` property is read-only while `layers` is read-write.

I tried to keep all the properties in the properties table read-write, the rest being read-only or methods. I might have messed up for some?

**Comment by robintindale** [comment]
Ah OK that wasn't clear. Perhaps needs making more explicit? I think it's a bit harder to parse when properties and methods are mixed, means you have to read the description and/or code each time.

In general, I find the new format harder to parse, because everything jumbles into everything else. 

I think contributing reasons are:
* everything is on one massive page, so you can quite easily scroll into another object's methods / properties without noticing. This may be a problem with the visual hierarchy of the sections, but I think it would be a problem even if the titles were massive 😁 
* methods and properties are not clearly delineated, could be done with `()` on the end of methods, but the different treatment of read-only and read-write properties also contributes
* the sidebar / method title is sometimes not the method name i.e. `getSelectedDocument` is called `Accessing the selected document` and only reading the code yields the method name. I thought this was only for `Class`-level methods, but `Settings` doesn't follow this convention

Will have a think because I feel there are some other usability things I can't quite put my finger on

Noticed another small inconsistency - the type of `layers` for `Group` is `Layer` (when it's an array?) whereas the type for `overrides` on `Symbol Instance` is `Override[]`

**Comment by mathieudutour** [comment]
> everything is on one massive page, so you can quite easily scroll into another object's methods / properties without noticing. This may be a problem with the visual hierarchy of the sections, but I think it would be a problem even if the titles were massive

Hum interesting, I actually find it a lot more easier. I tried to look at the best documentations around and one that really strike me was https://stripe.com/docs/api. We can probably improve the design and the usability but I really like those type of documentation where you are just a ctrl + f away from anything

> could be done with () on the end of methods

Good idea

> the different treatment of read-only and read-write properties also contributes

Yes I agree. My end goal is to only have read-write properties and methods. I find read-only properties confusing. So hopefully this will naturally disapear :)

> the sidebar / method title is sometimes not the method name

Indeed. I'd say that a human readable title is preferable but can be argued either way.

> the type of layers for Group is Layer (when it's an array?) whereas the type for overrides on Symbol Instance is Override[]

Typo. Good catch!

**Comment by robintindale** [comment]
> I tried to look at the best documentations around and one that really strike me was https://stripe.com/docs/api. We can probably improve the design and the usability but I really like those type of documentation where you are just a ctrl + f away from anything

yep true - they have one of the best single pagers. One thing I've noticed is that they always use full english descriptions in the sidebar / titles - never method names. We are currently mixing full english and method names in sidebar / titles, so perhaps we should gradually move to all english or all method names. 

Github also uses full english descriptions https://developer.github.com/v3/orgs/outside_collaborators/ and I like the summary at the top of an object. This helps with the fact that the sidebar hides most of a full english description

I think that's one thing I'm missing from the old docs is a way to get an easy overview of an object - properties, static methods & instance methods. Admittedly this doesn't exist in Stripe, but it was super clear in 48, with inheritance, static methods, members, constructors all having a known format. Maybe reintroducing `WrappedObject` could help with inheritance (and would make the `Sketch Components` section more practical - and a more clear inheritance tree, like 48

![image](https://user-images.githubusercontent.com/2700528/37396099-d681cfb6-276f-11e8-9a6f-295e281aa3a1.png)

Overall, it would be cool to distinguish between static methods, constructors, members & methods somehow, and for these to have a consistent format across the docs (and maybe representation in the sidebar, although if we go full english description route - probably not)

> Yes I agree. My end goal is to only have read-write properties and methods. I find read-only properties confusing. So hopefully this will naturally disapear :)

There are some things it's kinda weird to reassign (like a Layer `id` or the Document `pages`) but I guess that can still be possible and people just shouldn't do it :)

**Comment by mathieudutour** [comment]
> we should gradually move to all english

:+1:

> the summary at the top of an object

Oh yes that's nice indeed. But I'm scared that it will get out of sync with the actual content :/

> a more clear inheritance tree

That reminds me that I wanted to make a diagram with the inheritance tree. Maybe that would help solve the issue. But I like the idea of the breadcrumb for each component yes

> There are some things it's kinda weird to reassign (like a Layer `id` or the Document `pages`)

So I was thinking that instead of separating the hopefully really rare read-only properties, we could throw a descriptive error when trying to write them. That way you get in-context documentation without polluting the main docs with often usuless information (if you don't do weird stuff, you won't need it). How does that sound?

**Comment by mathieudutour** [comment]
I made some progress in the right direction I believe: https://developer.sketchapp.com/reference/api/

**Comment by robintindale** [comment]
> scared that it will get out of sync 

OK so a question - are these docs generated from / synced with the source files? I'm guessing S48 docs were (from their appearance), but the new ones are just markdown files? Doesn't that mean the docs can get out of sync anyway (regardless of a "object summary")?

I guess the fix would be to generate the summaries dynamically from the markdown files or another intermediate form. The markdown files could also be generated out of comments on the source files, but I'll let you comment on whether  / why we don't want to do that.

> diagram with the inheritance tree

ah like for everything in one? that sounds useful, although I still think its cool to have the breadcrumbs

> we could throw a descriptive error when trying to write them

yep this sounds good :) 

Thinking about properties, and seeing https://github.com/sketchplugins/plugin-requests/issues/17, it seems like we need to be clearer when an assignment will travel up the reference tree, and when it won't. i.e. `layer.frame.x = 2` doesn't change the frame, when the user would really expect it to do so.

> made some progress in the right direction 

yep you did :) I really like the new properties / params table

A few things I noticed
* `Font` : `font` and `systemFontSize` are write-only properties?
* the `Returns` for the `Move the layer in the hierarchy` methods is very teeny 🐜 
* inconsistent capitalisation i.e. `create a new Text` and `Create a new shape`. Guess we need a rule about whether we capitalise object names or not
* `Access the selected document` and friends can have a `Returns` with the `Document` type
* For methods that return the current X, like `Adjust to fit its children`, should X be a reference to the `Document` object
* code titles like `ImageData` are very small relative to normal titles
* when it comes to properties / inherited properties, I see we quite often repeat the inherited properties (like `Shape`) isn't this a bit pointless if the inheritance is clear. Isn't it better for people to only see the unique stuff, and have a better understanding of which properties come from where
* `Create a new Symbol Master from an Artboard` SymbolMaster should be linkified?
* Hotspot has a property `layers` which is wrong? When I call it, it's `undefined` and it doesn't seem to make sense
* objects need linkifying in `objectToExport`> export parameters

that's all I had time to spot atm

**Comment by mathieudutour** [comment]
> Doesn't that mean the docs can get out of sync anyway (regardless of a "object summary")?

They can but it's easier to check that a PR doesn't modify the docs rather than remember that the object summary needs to be updated as well.

> the fix would be to generate the summaries dynamically from the markdown files

Possibly. I'll think about it.

> The markdown files could also be generated out of comments on the source files, but I'll let you comment on whether / why we don't want to do that.

Because when you try to put all the examples, all the human-readable explanations, and all of that in the source code, it's becoming unreadable. Also the parser for those comments is far from trivial and I couldn't find any that generate something clean.

> I still think its cool to have the breadcrumbs

Agree

> sketchplugins/plugin-requests#17

Sounds like a bug that we should fix. Everything should travel up

> Isn't it better for people to only see the unique stuff, and have a better understanding of which properties come from where 

That's a good question. What I tried to do:
- put the inherited properties first
- put the unique stuff after
So it's easy to parse. I feel like writing all the properties everytime would help beginners. Maybe we can  add a stronger border between inherited and defined properties?

> Hotspot has a property layers which is wrong?

Indeed

**Comment by robintindale** [comment]
> all the human-readable explanations, and all of that in the source code, it's becoming unreadable

OK makes sense :)

> stronger border between inherited and defined properties

yeah that would be great, and maybe a subtitle `Inherited from X`

> I'm not sure I understand

Ah I just mean like for https://developer.sketchapp.com/reference/api/#adjust-to-fit-its-children it should say the current `Group` where `Group` links to https://developer.sketchapp.com/reference/api/#group
