### ISSUE TITLE
docs - flow.backtarget needs description

### ISSUE THREAD

**Issue by robintindale** [BohemianCoding/SketchAPI#123]
http://developer.sketchapp.com/reference/api/#flowbacktarget has no explanation. You can infer the use from the code, but a description would help out

**Comment by robintindale** [comment]
btw if you'd rather put these issues on https://github.com/BohemianCoding/developer.sketchapp.com repo lmk, I just found that the `md` files are located here

**Comment by mathieudutour** [comment]
the https://github.com/BohemianCoding/developer.sketchapp.com repo is being archived, everything is moving here so that it's easier for every body :)

Indeed I missed that description

**Comment by mathieudutour** [comment]
fixed in 09e2360
