### ISSUE TITLE
Page 'Selected Layers' links to Document

### ISSUE THREAD

**Issue by robintindale** [BohemianCoding/SketchAPI#128]
Clicking `Page > Selected Layers` in the left sidebar jumps to `Document > Selected Layers`

I think this is because the # links are relying on unique names - whereas `Selected Layers` is on both `Document` and `Page`

**Comment by robintindale** [comment]
Same with `Text > adjustToFit`

**Comment by mathieudutour** [comment]
fixed, good catch
