### ISSUE TITLE
Set layer data from a layer instance

### ISSUE THREAD

**Issue by nichenqin** [BohemianCoding/SketchAPI#129]
Currently, we can set setting on a layer through `Setting` API:
`Setting.setLayerSettingForKey(layer, key, value)`.
How about implement an instance method in `Layer` to set data from a layer instance:
```javascript

layer.setData(key, value)
```

**Comment by mathieudutour** [comment]
I'd prefer to keep the functionality silloed. What's would be the advantage of having it as a layer method?

**Comment by nichenqin** [comment]
For example, I can chain the method with other instance method; Or I can `bind` the method to another layer when I use the chain; And If I want to set all key value pairs of an exist object as data to an exist layer, I can implement another function to use with lodash `toPairs` method
```javascript
function setData(pair) {
  existLayer.setData(...pair)
}

const obj = {a: 1, b: 2}
_.toPairs(obj).forEach(setData)
```

It is just a code style, and I admit it is dispensable, it will just be a little more clear for me : )

**Comment by mathieudutour** [comment]
you can already bind them: `const setDataForLayer = Settings.setLayerSettingForKey.bind(this, layer)`

Let's keep it like this for now :)
