### ISSUE TITLE
Documentation errors/improvements

### ISSUE THREAD

**Issue by matt-curtis** [BohemianCoding/SketchAPI#131]
Hey Mathieu and team,

Took the new API for a test drive today. Major improvement from the old way of doing things! The documentation needs some tweaks here and there to match, though. Some of the issues I noticed were addressed in other Issues, so I'll just point out the things I didn't see mentioned elsewhere:

- `Layer.parent` is mutable, and moves layers between different groups/parents. I had to guess to find this one.
- `Text.fragments` contains a `range` property that tells what range of text within the text layer the fragment encompasses.
- `Rectangle` is documented as being defined on `Sketch.Document` when it is in fact on `Sketch` (which makes more sense to me). This one puzzled me a bit till I did some testing.

That's it for now. Once again, great work - can't wait to see what else is in store.

**Comment by mathieudutour** [comment]
> Layer.parent is mutable, and moves layers between different groups/parents. I had to guess to find this one.

All the properties are mutable except specified otherwise. In the end, I want only want read-write properties and methods. I find read-only properties confusing

> Text.fragments contains a range property that tells what range of text within the text layer the fragment encompasses.

Good catch.  I'm thinking about how to improve that API, I really don't like it.

> Rectangle is documented as being defined on Sketch.Document

Where do you see that?

**Comment by matt-curtis** [comment]
> Where do you see that?

Here: https://developer.sketchapp.com/reference/api/#rectangle

Another note:

- `Group` is defined on `Sketch` directly, and not on `Sketch.Document`.

**Comment by mathieudutour** [comment]
`sketch/dom` !== `Sketch.Document`

you can think of it as:

```js
require('sketch') === {
  ...require('sketch/dom'),
  UI: require('sketch/ui'),
  Settings: require('sketch/settings'),
  Async: require('sketch/async')
}
```

**Comment by matt-curtis** [comment]
Ah, I see. That clears a lot up! Is it possible to make that a little bit clearer?

**Comment by mathieudutour** [comment]
there is a bit of information here: https://developer.sketchapp.com/reference/api/#installation

Feel free to send a PR with a clearer explanation (https://github.com/BohemianCoding/SketchAPI/blob/develop/docs/api/installation.md) 😃

**Comment by matt-curtis** [comment]
I'll give it a shot if I find the time. The example you gave just now above is actually a pretty good one :)

**Comment by mathieudutour** [comment]
Cool 👍 I'll close this as the initial issue is fixed :)
