### ISSUE TITLE
No way to exert precise control over a layer's index

### ISSUE THREAD

**Issue by matt-curtis** [BohemianCoding/SketchAPI#134]
Assigning to `Layer.index` has no effect, as it is not mutable. Am I misunderstanding how this API is supposed to be used? The current API seems to suggest something more like `while(layer.index != 3) layer.moveBackward()` or such, which is a little brutish.

**Comment by mathieudutour** [comment]
This is coming from the previous API. I'm actually struggling to understand the use-case for it.
Do you have some examples of when and how you would use that? That would help shaping the API

**Comment by matt-curtis** [comment]
Well, what I'm precisely trying to do is to position a layer directly before/after another layer. So an API method to that affect would solve much of the common use case, I think.

**Comment by mathieudutour** [comment]
I see. Then maybe I should just make `layer.index` and remove all the `layer.moveBackward` API

**Comment by matt-curtis** [comment]
I think the `layer.moveX` are still useful as convenience APIs. Really what I think is needed is a `layer.insertAboveLayer` or `layer.insertBelowLayer`. `layer.index` (imo) doesn't really need to become mutable to solve what is the most common use case.

**Comment by mathieudutour** [comment]
yeah but I don't want to expand the API surface if I don't have to. `layer.insertAboveLayer` (`layerA.index = layerB.index`), `layer.moveX` (`layer.index++`) can easily be implemented by mutating the index.

**Comment by matt-curtis** [comment]
I'd say `layer.index` might be sufficient so long as as it's clear what direction assignment, incrementation, deincrementation have on a layer, which requires a sufficient mental model of how the Sketch layer stack works. The `moveX` APIs are very clear. One place that assigning to `layer.index` falls short is that you'd have to do `layer.index = layer.parent.children.length - 1` (or some such) to move to the bottom (or top? I'm forgetting exactly how the stack works now that I'm not looking at it.) which is more verbose.

**Comment by mathieudutour** [comment]
I'm hoping that some examples of the most common use cases will be enough to build a mental model.
In any case, I won't remove the existing `moveX` without first deprecating it and providing enough documentation :)
