### ISSUE TITLE
Text API: line fragments are always full-width

### ISSUE THREAD

**Issue by matt-curtis** [BohemianCoding/SketchAPI#135]
Is it possible for the `Text.fragments` to report more precise rectangles? While it's great to be able to get the individual rectangles of each line, the width of the rectangles is always equal to that of the text layer. Since it's not difficult to get the width of the layer itself, it would be more useful if it returned the actual width of the line as fitted to its characters.

**Comment by mathieudutour** [comment]
I'm also struggling to understand the use case for the fragments.

I was thinking about having an API which I find easier to reason about:
instead of fragments and ranges, you would have an array of `span`. Each span would be an object:
```js
{
  text,
  font,
  paragraphStyle
}
``` 
If you put all the span together, you would get the total text value (still exposed as `text`). 

What do you think?

**Comment by matt-curtis** [comment]
What would each "span" encompass, if not line fragments? From some of the discussions over sketchplugins.com it would seem a lot of people would like to be able to iterate over the segments of text layer in order to get styling, which seems like the use case 'span' is used for.

For example, my [Sketch Highlighter](https://github.com/matt-curtis/Sketch-Highlighter) plugin needs to be able to get line rectangles in order to work. I've got an initial implementation of it that tries uses the new Text fragments API [here](https://github.com/matt-curtis/Sketch-Highlighter/blob/sketch-49-js-api/Sketch-Highlighter.sketchplugin/Contents/Sketch/script.js#L68).

**Comment by mathieudutour** [comment]
Hum actually I got mixed up a bit.

What I'm thinking for `spans` would be a way to represent the NSAttributedString without relying on ranges which are hard to reason about and can easy break rendering (some characters like emojis have a length > 1 so if you set a range that would split the emoji, it will break the rendering). The spans are basically an array of different styles with the text value attached to it.

It means that it can span over multiple lines (if the style doesn't change). So a rectangle doesn't make much sense but maybe we can have the coordinate of the starting point and ending point?

Line fragments might still make sense then?

**Comment by matt-curtis** [comment]
Maybe the problem could be solved by having a property named `styledTextFragments` that returns the information you described (`{ text, font, paragraphStyle }`) that also includes a `range` property (doesn't have to actually be an NSRange, maybe an intermediary `Range` object). That `range` could be plugged into another `Text` API method to get information on text positioning, something like `Text.getTextRectangles(range)`. If the `range` parameter is `null`, it returns the text rectangles for the entire string in the text layer. The `Range` object could also be constructed manually (`new Text.Range(5, 120)`) for more specificity?

**Comment by mathieudutour** [comment]
Oh yes that's a good idea. I don't think I would expose the `range` on a `styledTextFragment` but it can be a non-enumerable property.

So `textLayer.getTextRectangles` would accept:
- `null`/`undefined` -> all the line fragments
- a `styledTextFragment` -> the line fragments of the text fragment
- an array of `styledTextFragment`
- an object `{location, length}` -> the line fragments of the range
- an `NSRange` -> the line fragments of the range

**Comment by matt-curtis** [comment]
> So textLayer.getTextRectangles would accept:

It sounds like a little bit more work to implement and test all those cases (vs. a single range argument), but as far as convenience yes, that sounds fantastic.
