### ISSUE TITLE
Layer API: add ways to manipulate opacity and rotation

### ISSUE THREAD

**Issue by matt-curtis** [BohemianCoding/SketchAPI#136]
- [x] opacity (#142 )
- [ ] rotation

**Comment by matt-curtis** [comment]
@mathieudutour Quick question - what's the release cycle for JS API changes like? Trying to make some plans around when to expect the current crop of changes to hit.

**Comment by mathieudutour** [comment]
Because the API is bundled in Sketch, it is released at the same time as Sketch.

**Comment by matt-curtis** [comment]
Right, but not all features-in-progress of the JS api come out when a new Sketch release does. What I'm trying to get a handle on is when rotation & opacity will drop.

**Comment by mathieudutour** [comment]
I haven't started to work on rotation yet so it won't be with Sketch 50. opacity will be tho

**Comment by matt-curtis** [comment]
Did you have any specific ideas for what the API might look like besides a simple `rotation: Number` property on `Layer`? I might be able to take a crack at it.

**Comment by mathieudutour** [comment]
I wasn’t entirely sure. There are 2 solutions:
- put it at the root of the object
- put it in a `layout` sub-field alongside `flippedVertically`, `flippedHorizontally` and the contraints 

What do you think?

**Comment by matt-curtis** [comment]
Probably a variation of the second.

Something like:

`Layer.transform`: containing `rotation: Number`, `isFlippedVertically: Bool`, `isFlippedHorizontally: Bool`.

and

`Layer.constraints`: containing `isPinnedTop: Bool`, `isPinnedRight: Bool` (and so on) then `isWidthFixed: Bool`, and `isHeightFixed: Bool`.

**Comment by mathieudutour** [comment]
Sounds good

**Comment by matt-curtis** [comment]
Hi @mathieudutour - I'm writing an article for Smashing Magazine about sketch plugin development that happens to need the ability to rotate a layer. Right now, I'm using `layer.sketchObject.rotation`, but it would be more ideal if I could just do `layer.rotation` or `layer.transform.rotation`. Any chance this is in the pipeline?

Thanks,
Matt

**Comment by mathieudutour** [comment]
Oh thanks for reminding me, I had a WIP branch that I just push. I’ll finish it next week.

Btw, you should probably use `userVisibleRotation` instead of `rotation` as they are opposed and the one you see in Sketch is `userVisibleRotation`

**Comment by matt-curtis** [comment]
Thanks! I'll be keeping an eye out. Also thanks for the note on `userVisibleRotation`.
