### ISSUE TITLE
Will we get events as well?

### ISSUE THREAD

**Issue by bensmeets** [BohemianCoding/SketchAPI#14]
To be able to listen to in plugins. Stuff like "on new layer created", "on symbol renamed", etc. ? Or is that too much regarding performance (which is hanging by a thread as it is ;) ).

**Comment by bomberstudios** [comment]
There's already an Actions API. See an example at http://developer.sketchapp.com/examples/plugins/selection-changed/, and a list of events at http://developer.sketchapp.com/reference/action/ : )

**Comment by bensmeets** [comment]
Very cool stuff, but what I meant was, will this JS wrapper provide some api for those events as well? Or is that a silly question :)

**Comment by bomberstudios** [comment]
Events are dealt with in a plugin's `manifest.json` file, so they don't really care whether your script uses the JS API or the old style : )

**Comment by bensmeets** [comment]
Ah, didn't know that. Good to know thanks.

**Comment by mossyblog** [comment]
technically the API will likely need a pub/sub event model. For instance pumping an event to ReloadInspector once you adjust a SharedStyle .. that or invoke an event to Sync sharedstyles via code.
