### ISSUE TITLE
Rectangle properties and functions do not work

### ISSUE THREAD

**Issue by juliussohn** [BohemianCoding/SketchAPI#143]
The rectangle functions, that are used to modify layer frames do not work. I can read the values, but setting them has no effect.

```javascript
log(document.selectedLayers.layers[0].frame.height) // -> 200

document.selectedLayers.layers[0].frame.height = 100

log(document.selectedLayers.layers[0].frame.height) //  -> 200
``` 
Same for the `offset()` function.

Here's a temporary workaround: https://github.com/sketchplugins/plugin-requests/issues/17

**Comment by mathieudutour** [comment]
to be clear,
this works:
```js
var layer = document.selectedLayers.layers[0]

layer.frame = {
  x: layer.frame.x,
  y: layer.frame.y,
  height:100,
  width: layer.frame.width
}
```

this doesn't:
```js
document.selectedLayers.layers[0].frame.height = 100
```

**Comment by eonist** [comment]
@mathieudutour  Just crashes my sketch 😭

**Comment by mathieudutour** [comment]
what crashes your Sketch?

**Comment by eonist** [comment]
Trying to set frame to layer.frame. 

Doing this worked ✅
```javascript
layer.frame().setWidth(100);
layer.frame().setHeight(100);
layer.frame().setX(0)
layer.frame().setY(0)
```

**Comment by mathieudutour** [comment]
your `layer` isn't a a Layer from the API

**Comment by eonist** [comment]
If I make a rectangle and copy paste this exact code: 

```javascript
var layer = document.selectedLayers.layers[0]

layer.frame = {
  x: layer.frame.x,
  y: layer.frame.y,
  height:100,
  width: layer.frame.width
}
```

It crashes sketch 47.1 🤷

**Comment by mathieudutour** [comment]
The API has been introduced in Sketch 49 and this bug has been fixed in Sketch 50
