### ISSUE TITLE
Add a wrapper object for Slice layers

### ISSUE THREAD

**Issue by thierryc** [BohemianCoding/SketchAPI#150]
How is the best way to access (or create) to a slice layer ?
PR #31 is outdated ?

Connect BohemianCoding/Sketch#16184

**Comment by mathieudutour** [comment]
The PR is indeed outdated and there is no wrapper for a Slice yet.

**Comment by thierryc** [comment]
Dear Mathieu,

Yes, I will try to. 

I read the export method. For the moment the parameter can be a layer, an array of layers, a page or an array of pages. It should be a slice and an array of slice to.

I have tried to figure out how the API deep works. I now have a first understanding.
What method do you want to expose in the API ? 

Naming is difficult. Do you have any suggestion for the naming of the slice "method" ?
Do you have naming convention ?

**Comment by mathieudutour** [comment]
What method are you talking about?
