### ISSUE TITLE
SketchAPILocation How to restore the default API Location ?

### ISSUE THREAD

**Issue by thierryc** [BohemianCoding/SketchAPI#152]
Hi,

How to restore the default API Location after I change it ?

I will try to add slice support to the API, but before to start, I need to know how to get my configuration back at the normal.

```
defaults write com.bohemiancoding.sketch3 SketchAPILocation "/path/to/your/SketchAPI.js"

```

Thank you

**Comment by mathieudutour** [comment]
it would be `defaults delete com.bohemiancoding.sketch3 SketchAPILocation`.

Thanks for looking into it!
