### ISSUE TITLE
npm run test Grep error

### ISSUE THREAD

**Issue by thierryc** [BohemianCoding/SketchAPI#153]
This line in the .gitignore file generate a grep error when I run test. 

```examples/**/package-lock.json```

```grep: repetition-operator operand invalid```

```
npm run test

```

**Comment by thierryc** [comment]
For user without the Xcode Sketch build ... ;-)

Change 
"run-tests": "skpm-test app=xcode", 

To
"run-tests": "skpm-test",

**Comment by mathieudutour** [comment]
Ah yes, you might need to install the GNU version of grep with `brew install grep --with-default-names`.

But it's probably easier to example the `examples/**/package-lock.json` to their real path, not too much a hassle to manually add a new one when we add an example. Happy to accept a PR for that

**Comment by thierryc** [comment]
ok
