### ISSUE TITLE
constructors return (null) without parent param

### ISSUE THREAD

**Issue by robintindale** [BohemianCoding/SketchAPI#156]
```
var text = new sketch.Text({
  text: 'my text',
  alignment: sketch.Text.Alignment.center,
})
```
returns `(null)` 

```
var text = new sketch.Text({
  parent: page,
  text: 'my text',
  alignment: sketch.Text.Alignment.center,
})
```
returns the layer and inserts it into a page.

```
var text = new sketch.Text({
  text: 'my text',
  alignment: sketch.Text.Alignment.center,
})
page.layers = [text];
```
works fine, so the layer is clearly being constructed OK behind-the-scenes.

I think the `(null)` printing is the misleading bit, as the top example is the constructor example from the API and so I thought it was broken when it was printing `(null)`

tested happening on `Text`, `Group` and `Shape`, so I assume all `Layer` ones

**Comment by mathieudutour** [comment]
yes I think it's because of the way `log` works. If you log `text.toJSON()` does it work?

I've reworked how the logging works in Sketch 50, with first class support `console.log` so it should disappear naturally.

(logging a Page also prints `(null)`)

**Comment by robintindale** [comment]
yeah `toJSON()` works - the object is valid behind-the-scenes. Yep I see `console.log` working OK in `Sketch 50` - will close this, hopefully doesn't trip anyone up in the interim :)
