### ISSUE TITLE
NSTask launch path not accessible

### ISSUE THREAD

**Issue by yordanoff** [BohemianCoding/SketchAPI#159]
Hey everyone!

I created a small plugin that helps with the optimization of PDF files. It's based on the SVGO Example by Sketch (here: https://github.com/BohemianCoding/plugins.examples.svgo-export).

I run a Ghostscript command using NSTask.

Unfortunately, on some versions of macOS (High Sierra, 10.13.3) it doesn't work. What I get in the Console is `launch path is not accessible`, even though the shell is bash and its location is correct; there is a PATH set, too.

The demo example by Sketch (SVGO) also doesn't work on 10.13.3.

Here is the function:

```

function mergePDF(folderPath) {
    var task = NSTask.alloc().init();
        task.launchPath = "/bin/bash";

    var args = [
        "-l",
        "-c",
        'gs \
            -dPDFSETTINGS=/printer \
            -dNOPAUSE \
            -sDEVICE=pdfwrite -sOUTPUTFILE=' + folderPath + '/' + fileNameMerge + '\
            -dBATCH ' + folderPath + '/*.pdf'
    ];

    task.arguments = args;
    task.launch();
    task.waitUntilExit();

    return (task.terminationStatus() == 0)
}

```

Do you have an idea how this could be fixed?

Thanks a lot!
Joro

**Comment by mathieudutour** [comment]
If the demo example doesn’t work for you, I’m guessing there is something wrong with your config. 
Looks like it doesn’t manage to find `/bin/bash` for some reason

**Comment by mathieudutour** [comment]
But that’s not really a bug related to the API so I’m going to close this. You might find your answer here: http://sketchplugins.com
