### ISSUE TITLE
Gradient missing documentation

### ISSUE THREAD

**Issue by robintindale** [BohemianCoding/SketchAPI#166]
Don't think Gradient / GradientStop is documented, despite being referenced https://github.com/BohemianCoding/SketchAPI/blame/develop/docs/api/Style.md#L159

Noticed when reviewing the changes from #142

**Comment by mathieudutour** [comment]
fixed in https://github.com/BohemianCoding/SketchAPI/commit/c259ae0a3cf39e73de133fcef832db0c0f841215
