### ISSUE TITLE
Diffs between what ships with Sketch and what builds with this repo

### ISSUE THREAD

**Issue by kgn** [BohemianCoding/SketchAPI#18]
I just got the project building with the new instructions, but noticing a pretty dramatic difference between the file that ships with Sketch 40.3 (33839) and what builds.

The built js file has 1248 lines of code, while the file that ships with Sketch has 2111.

**Comment by kgn** [comment]
Looks like this is probably just due to changes

**Comment by kgn** [comment]
Getting more up to speed with the repo, it appears that the `develop` branch is much further along than master and is more aligned with what's shipping in Sketch today?

**Comment by bomberstudios** [comment]
Yep. As we've explained on the comments of various issues, this is still a work in progress and so far we haven't really _released_ the project.

I'll add a note to the README to clarify the status of the project, thanks for asking!

**Comment by kgn** [comment]
I understand that this is still a work in progress, I guess what I'm really getting at with this issue is trying to identify issues I think eager developer/designers like myself will run into when trying to figure out how best to provide community support and pull requests :)

If I may propose:
- `master` is always the latest of what is shipping with Sketch.
- `develop` is the latest of what's going into the next release of Sketch.
- When a new release of Sketch is released, tag the repo with the corresponding version
- Adding a contributor guide that outlines this, some common code conventions for the project, and the roadmap of things in the works that the community could contribute to.

I'm eager to contribute and see this get to a non-wip version 👍

**Comment by plrthink** [comment]
It would be great if there's a note on the README to show the status of this API like bundled in Sketch.app or not and which version of Sketch has this API bundled in.

**Comment by mattpfeffer** [comment]
Out of interest, is there a way to force Sketch to run a less stable branch of the API?

**Comment by kgn** [comment]
@mattpfeffer the README outlines how to build the code with `gulp` and set the `SketchAPILocation` to point to your own SketchAPI file: https://github.com/BohemianCoding/SketchAPI#development

**Comment by mathieudutour** [comment]
there is a branch for each release of Sketch if you need to check what is ship with each of them
