### ISSUE TITLE
What is resizingType?

### ISSUE THREAD

**Issue by kdawg1406** [BohemianCoding/SketchAPI#182]
I'm parsing the JSON for my Sketch file.

I see a property, **resizingType**.

Can someone please tell me what this is, how it is used, and how to interpret the value?

Much appreciated, thank you in advance.

Karl

**Comment by robintindale** [comment]
Does this help? http://sketchplugins.com/d/54-change-resizing-method-for-mstextlayer

**Comment by kdawg1406** [comment]
@robintindale  thank you.  

Too bad Sketch does not provide docs for the properties their JSON files.

**Unofficial**:  Text from Robin's link:
0 = Stretch
1 = Pin to corner
2 = Resize object
3 = Float in space

**Comment by mathieudutour** [comment]
you might want to have a look at https://github.com/mathieudutour/graphql-x-sketch which gives you some (very crude) docs for the JSON files through the graphiQL editor. More specifically, the list of enums is here: https://github.com/mathieudutour/graphql-x-sketch/blob/master/lib/schema/Scalars.js

**Comment by kdawg1406** [comment]
@mathieudutour this is a goldmine of information. thank you.  Strange that Google does not return results for these awesome pages when I search for "LayerResizingType" or "resizingType"  

Again, thank you very much.  I should have posted here 2 months ago.

Best,

Karl
