### ISSUE TITLE
return a Buffer from an export instead of writing to file

### ISSUE THREAD

**Issue by jay7n** [BohemianCoding/SketchAPI#185]
Hi guys, 

Is there a way (such an API) to acquire the thumbnail view's data from the layer inspector, which is highlighted in the below picture with a red rectangle?   I need this kind of data ( as a NSImage type) to do some image comparisons. 

![default](https://user-images.githubusercontent.com/1228472/39345492-46fb46f0-4a1b-11e8-8f5b-6e6aea73dffd.png)

Thanks in advance !

**Comment by mathieudutour** [comment]
the [`export`](https://developer.sketchapp.com/reference/api/#export) API only write to a file. We discussed with @bomberstudios about a way to return an `NSData` if an option is specified but it's not possible with the API yet

**Comment by jay7n** [comment]
Is this (returning NSData from the export) being developed ? would appreciate it if I could know how long I have to wait to use it ... honestly I got stuck here and can't step any further. 

If it's impossible to expect it in a near future, do you have any kind suggestions for some alternative ways to do the job ? 

Thanks for your time again ~

**Comment by robintindale** [comment]
You can use the old API for now, being aware of the disadvantages
```
  var ancestry = MSImmutableLayerAncestry.ancestryWithMSLayer_(layer);
  var exportRequest = MSExportRequest.exportRequestsFromLayerAncestry_(ancestry).firstObject();
  exportRequest.format = 'png';
  var rend1 = MSExportManager.alloc().init().rendererForRequest(exportRequest);
  var rep1 = rend1.bitmapImageRep();
  var data = rep1.representationUsingType_properties_(NSPNGFileType, nil);
```

**Comment by jay7n** [comment]
thank you @robintindale I'll give it a try
