### ISSUE TITLE
Can't update image override by changing override.value

### ISSUE THREAD

**Issue by perrysmotors** [BohemianCoding/SketchAPI#190]
This doesn't work although the docs suggest it should (https://developer.sketchapp.com/reference/api/#symbol-override):

Given a selected symbol layer...

```
let imageOverrides = selectedLayer.overrides.filter(override => override.property === 'image');
let override = imageOverrides[0];
let image = new Image({image: '/Users/giles/Desktop/icon.png'});
override.value = image.image;
```
Both `override.value` and `image.image` are of type `ImageData`

The image in the override disappears instead of being replaced and the top area of inspector panel disappears too.

**Comment by mathieudutour** [comment]
just so you know, `let image = new Image({image: '/Users/giles/Desktop/icon.png'})` creates an image layer. You should be able to set the override directly to `'/Users/giles/Desktop/icon.png'` (once it is fixed)
