### ISSUE TITLE
getImportableSymbolReferencesForDocument returning symbols from a different library

### ISSUE THREAD

**Issue by steffanwilliams** [BohemianCoding/SketchAPI#195]
Hey guys,

I'm having an issue with Sketch 50's library API. Specifically, the `getImportableSymbolReferencesForDocument` function seems to be returning the incorrect symbols — or, it seems to be referencing a totally different library altogether:

```
var libraries = Library.getLibraries();
var library = libraries.find((library) => library.name === libraryName); // libraryName = "bui-web" in my case
var refs = library.getImportableSymbolReferencesForDocument(context.actionContext.document);
refs.find((symbol) => log(symbol.library.name)) // symbol.library.name = "bui-android", expected "bui-web". All symbols are from the wrong library.
```

Even when I explicitly point at the library that I want the symbols for, it gives me the wrong symbols:

```
var library = Library.getLibraryForDocumentAtPath('~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/biq.sketchplugin/Contents/Resources/libraries/bui-web.sketch');
var refs = library.getImportableSymbolReferencesForDocument(context.actionContext.document);
refs.find((symbol) => log(symbol.library.name)) // all symbols are from 'bui-android' library, despite explicitly importing bui-web.
```

Any help with this issue would be greatly appreciated.

**Comment by mathieudutour** [comment]
I don't seem to be able to reproduce 🤔 

Could you show the output of 
```
var sketch = require('sketch')
console.log(sketch.Library.getLibraries())
```
?

**Comment by steffanwilliams** [comment]
Absolutely...

```
[ { type: 'Library',
    id: 'F55B8C55-90F8-4303-99AA-167FDD09C007',
    name: 'iOS UI Design',
    valid: true,
    enabled: true,
    libraryType: 'Internal' },
  { type: 'Library',
    id: '91D2959D-9886-4DB7-A8B1-3E4004F1F8B0',
    name: 'bui-web',
    valid: true,
    enabled: true,
    libraryType: 'User' },
  { type: 'Library',
    id: 'E903DC0D-7995-42CC-B5D9-F17EC756A9D1',
    name: 'bui-media',
    valid: true,
    enabled: true,
    libraryType: 'User' },
  { type: 'Library',
    id: '91D2959D-9886-4DB7-A8B1-3E4004F1F8B0',
    name: 'bui-android',
    valid: true,
    enabled: true,
    libraryType: 'User' },
  { type: 'Library',
    id: '91D2959D-9886-4DB7-A8B1-3E4004F1F8B0',
    name: 'bui-web',
    valid: true,
    enabled: true,
    libraryType: 'User' },
  { type: 'Library',
    id: '91D2959D-9886-4DB7-A8B1-3E4004F1F8B0',
    name: 'bui-ios',
    valid: true,
    enabled: true,
    libraryType: 'User' },
  { type: 'Library',
    id: undefined,
    name: 'Apple iOS UI Design Resources',
    valid: false,
    enabled: false,
    libraryType: 'Remote' } ]

```

**Comment by mathieudutour** [comment]
oh so all your libraries have the same id.

So you want to open `bui-android`, `bui-ios` and `bui-web` and run
```
var documentData = context.document.documentData();
documentData.generateObjectID()
log('The current document ID changed to: ' + documentData.objectID());
```
and then save the file.

I don't think that's a bug in the API. Maybe in Sketch but that's a pretty niche use case so I'll close this

**Comment by robintindale** [comment]
I think it's slightly more than niche - if you simply copy and paste a Sketch file in Finder (perfectly reasonable to do) - they will have the same document ID and cause this problem when it comes to making them libraries.

As library IDs are the same as document IDs currently, I also suspect you could run into issues with the functionality of libraries too (getting confused where symbols are actually pointing). I agree it's not an API issue, but it's something good to feed upstream into Sketch. Maybe a simple detection of duplicate IDs at library add time (and reassignment then) would fix it

**Comment by mathieudutour** [comment]
actually I can fix this by checking if the name of the library is the same as well (that's what we do in Sketch as well)
