### ISSUE TITLE
Hope there is a way to get original MSLayer through "new Group"

### ISSUE THREAD

**Issue by ReadingSteiner** [BohemianCoding/SketchAPI#204]
I followed the guiding code at [here](https://developer.sketchapp.com/reference/api/#create-a-new-group)

However, I found the value it returns is a wrapped object from which I cannot access the original MSLayer.

The wrapped object looked like this:
![image](https://user-images.githubusercontent.com/6670037/41148531-c6128bb0-6b3b-11e8-8443-b85540f06e45.png)

**Comment by nichenqin** [comment]
You can access it through `layer.sketchObject`

**Comment by ReadingSteiner** [comment]
> You can access it through layer.sketchObject

Alright, thanks.

**Comment by robintindale** [comment]
docs for this function are here 👉 https://developer.sketchapp.com/reference/api/#sketch-components

**Comment by mathieudutour** [comment]
> Hope the docs could be better btw

PR welcome :)
