### ISSUE TITLE
SymbolInstance replace with new Symbol

### ISSUE THREAD

**Issue by tijmenvangurp** [BohemianCoding/SketchAPI#209]
I am trying to import symbols from a library and replace a local symbol instance with a library symbol similar to the replace with option in the context menu.

I don't think this possible yet in the API.
```
var instance = master.createNewInstance();
mylocalSymbolInstance = instance; // not working
```
I currently do this (without sketch API)

```
mylocalSymbolInstance.changeInstanceToSymbol(instance.symbolMaster());
```

Will this be possible in the future? Or am I doing something wrong here?

**Comment by mathieudutour** [comment]
you can already set the master of an instance:
```js
mylocalSymbolInstance.master = master
```

**Comment by tijmenvangurp** [comment]
works perfect thanks
