### ISSUE TITLE
Document.open() not working

### ISSUE THREAD

**Issue by bomberstudios** [BohemianCoding/SketchAPI#210]
According to the docs, running this code:

```
const sketch = require('sketch')
sketch.Document.open()
```

should open the file chooser panel. However, I'm getting this error:

```
ObjC method openDocument: requires 1 argument, but JavaScript passed 0 arguments
```

and no file chooser opens.

**Comment by mathieudutour** [comment]
so I'm confused, is this still an issue?

**Comment by bomberstudios** [comment]
It is, it’s just that my PR did the wrong thing.
