### ISSUE TITLE
Request: set color to text layer

### ISSUE THREAD

**Issue by tijmenvangurp** [BohemianCoding/SketchAPI#217]
I can now set color to shapes, and borders via the api. It would be nice if this also would be possible to set text color.
Currently I can only set a color like this:
`myTextLayer.sketchObject.textColor = MSImmutableColor.colorWithRed_green_blue_alpha(r,g,b,a);`
and would like to set a color like this:
`myTextLayer.color = '#ffffffff';`

**Comment by pburtchaell** [comment]
Came across the same issue today! Do you have a suggested workaround?

Here's a short example of what I'm doing:
```js
function applyFillToLayer(layer) {
  const { type } = layer;

  if (type === String(sketch.Types.Text)) {
    // how to apply color to text layer?
    // layer.textColor isn't available yet
  } 
  
  // apply new colors to shape layers
  if (type === String(sketch.Types.ShapePath) || type === String(sketch.Types.Shape)) {
    layer.style.fills = mapLayerFills(layer.style.fills, type)
    layer.style.borders = mapLayerFills(layer.style.borders, type)
  }
} 
```
