### ISSUE TITLE
Locked layers included in symbolInstance.overrides 

### ISSUE THREAD

**Issue by perrysmotors** [BohemianCoding/SketchAPI#219]
In Sketch, you cannot override an image if the corresponding layer in the symbol master is locked, so such layers should not be appear when accessing overrides from the API.

```
// The following array includes locked layers. It should not.
var overrides = symbolInstance.overrides
```

**Comment by perrysmotors** [comment]
It looks like the issue also applies for hidden layers

**Comment by mathieudutour** [comment]
Hum interesting. Setting the value of a locked or hidden override works just fine. Maybe we should add a field `userModifiable` or something?

**Comment by mathieudutour** [comment]
it's been renamed to `isEditable` so it'd be `override.sketchObject. isEditable()`
