### ISSUE TITLE
MSShapeGroup.shapeWithRect_ is not a function.

### ISSUE THREAD

**Issue by kgn** [BohemianCoding/SketchAPI#22]
The tests are failing because `Group.newShape` only makes rectangles and seems to be using a function that no longer exists: `MSShapeGroup.shapeWithRect_ is not a function.`

**Comment by bomberstudios** [comment]
Just to be sure: are you running the tests on Sketch 40.3 or Sketch 41 Beta?

**Comment by kgn** [comment]
No, this was on Version 40.3 (33839)

**Comment by mathieudutour** [comment]
The tests are passing now so I guess this has been fixed
