### ISSUE TITLE
Removing plugins is not fully documented

### ISSUE THREAD

**Issue by Kielan** [BohemianCoding/SketchAPI#229]
Having myself attempted to remove plugins I can confirm not only did following these steps not remove the folder from Application Support/com.bohem.../Plugins it did not edit the PLIST file, and also removing the plugin from the file did not fix the issue either, Sketch toolbox still crashes, using plugins is not possible, sketch otherwise works.

This page is both incomplete and seems to be incorrect documentation on how to remove a plugin. Solving the problem isn't actually necessary, giving the user the information to be able to know what actions sketch takes to register plugins is absolutely necessary for the end user and appears not currently available.

https://developer.sketchapp.com/guides/installing-plugins/

**Comment by bomberstudios** [comment]
I can't reproduce your issue here, can you please share more details about how you've installed the plugins?
