### ISSUE TITLE
MSImmutableColor.colorWithSVGString_ is not a function.

### ISSUE THREAD

**Issue by kgn** [BohemianCoding/SketchAPI#23]
The tests are failing because `Style.colorFromString` is using calling a function that appears to no longer exist: `MSImmutableColor.colorWithSVGString_ is not a function.`

**Comment by mathieudutour** [comment]
Hum I'm confused, the tests are working fine and `MSImmutableColor.colorWithSVGString_` do exist.

Also your fix still uses the function (`MSImmutableColor.colorWithSVGString_` and `MSImmutableColor.colorWithSVGString` are the same thing).

I'm going to close this, feel free to re-open with a specific repro
