### ISSUE TITLE
Cannot create an inner shadow with a blur of 0

### ISSUE THREAD

**Issue by evan-dickinson** [BohemianCoding/SketchAPI#230]
When I try to set the inner shadow on a layer, I can't set the blur to 0 -- the resulting blur is 3. Other values for blur work correctly, it's just 0 that fails.

To reproduce: create a rectangle, select it, and run this script:
```
var Style = require('sketch/dom').Style;
var Document = require('sketch/dom').Document

var document = Document.getSelectedDocument();
var selection = document.selectedLayers;
var item = selection.layers[0];

item.style.innerShadows = [
    {
		spread: 0,
		blur: 0,
		x: 1,
		y: 0,
		color: '#ebc100',        
    },
]
```

Results: The blur is set to 3, not 0.
<img width="384" alt="screen shot 2018-07-13 at 3 59 17 pm" src="https://user-images.githubusercontent.com/1036639/42717444-da99039e-86b5-11e8-80f1-74c1daeca32b.png">

This is with Sketch 51 (57462), on macOS 10.12.6.

**Comment by mathieudutour** [comment]
Ah stupid me, will fix it
