### ISSUE TITLE
Plugin is reloaded only after SketchApp is reopened

### ISSUE THREAD

**Issue by nicutimofte** [BohemianCoding/SketchAPI#239]
I'm working on a plugin which also contains a webview panel. 

These are my script: 
```json
  "scripts": {
    "build": "skpm-build",
    "watch": "skpm-build --watch",
    "start": "skpm-build --watch --run",
    "link": "./node_modules/.bin/skpm-link",
    "postinstall": "npm run build && skpm-link"
  }
```

The problem is that the plugin is not reloaded before running and also when disabling it from plugins section. 

Note: the caching is disabled with the following command:
```
defaults write ~/Library/Preferences/com.bohemiancoding.sketch3.plist AlwaysReloadScript -bool YES
```

**Comment by mathieudutour** [comment]
When you use a webview, your script is a "long-running" one which means that sketch will reuse the context (and so the previous code) when running the command again.

You can see more info here: https://github.com/skpm/skpm/issues/142
