### ISSUE TITLE
Sketch on Mac OS Mojave thumbnail bug

### ISSUE THREAD

**Issue by irrwood** [BohemianCoding/SketchAPI#247]
Sketch 51.2 at Mac OS Mojave thumbnail have a bug, OS will not render the thumbnails

**Comment by mathieudutour** [comment]
what do you mean by thumbnail?

**Comment by irrwood** [comment]
Blank space for Sketch file, unable to load preview. At the same time, the system will not generate all thumbnails including .sketch .png and .pdf.  Thumbnails refer to the "show icon preview".

**Comment by mathieudutour** [comment]
Oh I see. We are working on fixing the quick look bug. I'm going to close this issue since it's not really about Sketch API.

Thanks for the report
