### ISSUE TITLE
ReferenceError: Can't find variable: Rectangle

### ISSUE THREAD

**Issue by kgn** [BohemianCoding/SketchAPI#25]
Rectangle is not exposed to the global space so `parent.newGroup({"frame": new Rectangle(0, 44, 100, 44)});` fails.

Is it safe to add this to the top of `Rectangle.js`?

```javascript
function _Rectangle(x, y, width, height) {
  return new Rectangle(x, y, width, height);
}

__globals.Rectangle = _Rectangle;
```

This fixes the issue, but I'm not sure if there should be a global object named `Rectangle`, what do you guys think?

**Comment by mattpfeffer** [comment]
I don't think it's intended to be in the global scope. You can instantiate a rectangle object through the Application class. The following example works for me:

    sketch = context.api();
    var doc = sketch.selectedDocument;
    var pages = doc.pages;

    var firstPage = pages[0];    
    layer = firstPage.newText({text: 'Text Here!', frame: sketch.rectangle(100, 100, 10, 10), name: 'Document ID'});

**Comment by kgn** [comment]
It looks like this function was removed in the `develop` branch.

**Comment by mossyblog** [comment]
it's been changed to instantiation as opposed to just method invocation

`var artboard = newPage.newArtboard({frame: new sketch.Rectangle(0, 0, 100, 100), name:"New Artboard"});`

ie:

**new sketch.Rectangle(0, 0, 100, 100)**

**Comment by kgn** [comment]
Ahh, I'd tried `sketch.Rectangle(0, 0, 100, 100)`, that didn't work, but I missed adding `new`.
