### ISSUE TITLE
[Question] Data API?

### ISSUE THREAD

**Issue by harrisrobin** [BohemianCoding/SketchAPI#252]
Hello, please close this if it's not appropriate but I wanted to know if we can expect an API to load our own data sources via a 3rd party?

I know that Sketch 52 is in beta but I'm really looking forward to being able to do this so would be great to know if we can expect to be able to do it by the time it's in the Stable branch.

Thank you! 
:)
<img width="266" alt="screenshot 2018-09-20 10 14 39" src="https://user-images.githubusercontent.com/3880008/45824470-14964280-bcbe-11e8-84bb-7d678633dee4.png">

**Comment by mathieudutour** [comment]
Yep! Have a look here: https://github.com/BohemianCoding/SketchAPI/blob/develop/docs/api/DataSupplier.md
