### ISSUE TITLE
getSelectedDocument returns undefined when sketch app is not focused 

### ISSUE THREAD

**Issue by nicutimofte** [BohemianCoding/SketchAPI#253]
I'm working on a plugin which has an event triggered from outside of the sketch app - the action is not done in sketch. 
I'm using getSelectedDocument api and it returns undefined whenever the sketch app is not focused - notice that the document is open.

Any suggestion / workaround to solve this issue?
Thanks!

**Comment by mathieudutour** [comment]
You can try `const document = sketch.Document.fromNative(context.document)` as a workaround. 

I’ll fix this for the new Sketch version

**Comment by mathieudutour** [comment]
Even if it’s not an action there is a context

**Comment by nicutimofte** [comment]
You're right. Now I'm using as you suggested `const document = sketch.Document.fromNative(context.document)`, but unexpectedly it creates and opens a new sketch document(named "Untitled") and `document` contains the data of the newly created document.

**Comment by lucaorio** [comment]
@mathieudutour I see a merged PR, but I'm still experiencing this. Perhaps I'm doing something wrong?

```js
import { Document, Shape, UI, Style, Page } from "sketch";

const generate = () => {
  const document = Document.getSelectedDocument();
};

export default generate;
```

> console> undefined

**Comment by lucaorio** [comment]
That's great news, thanks! :)
