### ISSUE TITLE
[URGENT] Isometric Plugin not working in Sketch 52

### ISSUE THREAD

**Issue by sureskumar** [BohemianCoding/SketchAPI#259]
Hey guys,

Here is the error :(
Any help will be appreciated.

TypeError: MSShapeGroup.shapeWithBezierPath is not a function. (In 'MSShapeGroup.shapeWithBezierPath(newBezier)', 'MSShapeGroup.shapeWithBezierPath' is undefined)

How to define a shapeWithBezierPath in the new version?

Cheers
Sures

**Comment by mathieudutour** [comment]
```js
const shapeFromPath = MSShapeGroup.shapeWithBezierPath || MSShapeGroup.layerWithPath
```
