### ISSUE TITLE
Sketch 52.1 fails trying to set styles

### ISSUE THREAD

**Issue by coma** [BohemianCoding/SketchAPI#261]
This code is working properly on **Sketch 51.3**:
```js
import { Rectangle, Shape, Style } from 'sketch/dom';

export default function myCommand() {
  new Shape({
    name: 'sample',
    parent: context.document.currentPage(),
    frame: new Rectangle({ x: 0, y: 0, width: 300, height: 200 }),
    style: {
      fills: [
        {
          color: '#f00',
          fillType: Style.FillType.Color,
        },
      ],
    },
  });
}
```

but it fails on **Sketch 52.1** with:
```js
undefined is not an object (evaluating 't.copy')
```
furthermore removing the style prop like:
```js
import { Rectangle, Shape, Style } from 'sketch/dom';

export default function myCommand() {
  new Shape({
    name: 'sample',
    parent: context.document.currentPage(),
    frame: new Rectangle({ x: 0, y: 0, width: 300, height: 200 }),
  });
}
```
works on both versions.

Is there a new way to apply styles or is the new release API just broken?

**Comment by bomberstudios** [comment]
Sorry about that, we're working on a fix. Meanwhile, as a workaround, you can do:

```
s = new Shape({
  name: 'sample',
  parent: context.document.currentPage(),
  frame: new Rectangle({ x: 0, y: 0, width: 300, height: 200 })
})
s.style = {
  fills: [
    {
      color: '#f00',
      fillType: Style.FillType.Color
    }
  ]
}
```

(i.e: first create the shape, then set the style) which should work as expected.

Ping @mathieudutour.

**Comment by coma** [comment]
Wow @bomberstudios that was pretty fast!

Ok, so now it draws a red rectangle but keeps throwing the same error... Should I wrap it with a try/catch in order to keep my code safe?

**Comment by mathieudutour** [comment]
So it’s setting the style that throws an error on Sketch 52.1. Instead you can set the fill:
```js
s.style.fills = [...]
```

**Comment by coma** [comment]
Sure @mathieudutour, I've ended up wrapping the API with my own code and now it works (just an idea to check the solution):

```js
import * as Sketch from 'sketch/dom';

export class Shape extends Sketch.Shape {
  constructor({ style, ...props }) {
    super(props);
    if (style) { try { this.style = style; } catch(error) {} }
  }
}

export class Text extends Sketch.Text {
  constructor({ style, ...props }) {
    super(props);
    if (style) { try { this.style = style; } catch(error) {} }
  }
}

export class Artboard extends Sketch.Artboard {
  constructor({ style, ...props }) {
    super(props);
    if (style) { try { this.style = style; } catch(error) {} }
  }
}

export const { Page, Rectangle, Group, Style } = Sketch;
```

but now there is a new issue and I feel like it belongs to a new ticker (```initWithName_firstInstance``` is not a function?).

**Comment by coma** [comment]
Ok, forget about the ```initWithName_firstInstance```, [SharedStyle](https://github.com/BohemianCoding/SketchAPI/blob/develop/docs/api/SharedStyle.md) works just fine.

**Comment by mathieudutour** [comment]
fixed in https://github.com/BohemianCoding/SketchAPI/pull/260/commits/34a56db1ead5b54eae0d50d2f620c1679bba9b04
