### ISSUE TITLE
StyledLayer.sharedStyleId does not link style in Sketch inspector

### ISSUE THREAD

**Issue by WCByrne** [BohemianCoding/SketchAPI#268]
The follow works as expected
```javascript
var layer = new Shape({})
layer.sharedStyle = sharedStyle
layer.style.syncWithSharedStyle(sharedStyle)
```

Using `sharedStyleId` however seems to miss something causing the Sketch inspector panel to not show the linked style. 
```javascript
var layer = new Shape({})
layer.sharedStyleId = sharedStyle.id
layer.style.syncWithSharedStyle(sharedStyle)
```

Looking the implementation I'm not sure why this would happen. They appear to do the same thing under the hood. Maybe sending different String types to `this._object.setSharedStyleID(<id>)`?

**Comment by mathieudutour** [comment]
When you say "causing the Sketch inspector panel to not show the linked style", does it shows after you select something else and select it again?

**Comment by WCByrne** [comment]
I can't get it to show anyway I try - deselecting/reselecting, copy/paste, nothing updates the inspector when using the id.

**Comment by mathieudutour** [comment]
so you were trying that in the Run Script panel, weren't you? I think it's a bug with cocoascript and not with the API:
```js
var layer = new Shape({})
layer.sharedStyleId = sharedStyle['id']
layer.style.syncWithSharedStyle(sharedStyle)
```
works fine
