### ISSUE TITLE
get the font family and font size of a Text Object

### ISSUE THREAD

**Issue by easybird** [BohemianCoding/SketchAPI#269]
https://developer.sketchapp.com/reference/api/#font

It is totally unclear for me how to get the font family and font size of an existing Text object..
I see there is a way to set the font, but how to get the current fontStyles is unclear.

I search for this for several hours..and it seems like such a basic thing.. 😿

Can somebody help with this please?

This is what I seem to receive when looking at ```getSharedTextStyles```, but I don't see anything about fonts..:
```json{ type: 'Style',
  id: 'D85ABFCB-1F59-43B3-9771-89EC3A0F27F1',
  opacity: 1,
  blendingMode: 'Normal',
  borderOptions:
   { startArrowhead: 'None',
     endArrowhead: 'None',
     dashPattern: [],
     lineEnd: 'Butt',
     lineJoin: 'Miter' },
  blur:
   { center: { x: 0.5, y: 0.5 },
     motionAngle: 0,
     radius: 10,
     enabled: false,
     blurType: 'Gaussian' },
  fills: [],
  borders: [],
  shadows: [],
  innerShadows: [] }```

**Comment by kupe517** [comment]
I came here to see if I was missing something too. The array returned for text styles seems very incomplete at the moment. Would like it to return basic text properties like: font, font-size, color, line-height, alignment and character spacing
