### ISSUE TITLE
Get component JSON info through Sketch Api

### ISSUE THREAD

**Issue by yvanwangl** [BohemianCoding/SketchAPI#277]
I try to get Page JSON info through Sketch api like this:
```
export const exportCode = (context) => {
  var document = sketch.getSelectedDocument();
  const wrapPage = sketch.fromNative(document.selectedPage);
  console.log(wrapPage.toJSON());
};
```
I got an error:
![b429c625-70df-4520-986a-8810ccb7901e](https://user-images.githubusercontent.com/11405052/48064162-06669c00-e202-11e8-80a9-4a2a7d0650a0.png)

**Comment by mathieudutour** [comment]
What version of Sketch of you using?

**Comment by yvanwangl** [comment]
@mathieudutour Thanks for you apply :) , my sketch version is v 52.
I have make an very sample sketch file use Artboard \ Rectangle and Oval.

**Comment by mathieudutour** [comment]
If you update to v52.3 it should be fixed

**Comment by yvanwangl** [comment]
@mathieudutour Thank you , I will try.
