### ISSUE TITLE
Create a Font object, like how there is a Rectangle object

### ISSUE THREAD

**Issue by kgn** [BohemianCoding/SketchAPI#29]
Like `Rectangle` I think it might make sense to have a javascript object for `Font`. Right now `text.font` has to be set to a `NSFont` object, exposing the underlying obj-c objects. Also the `systemFontSize` defined as `set` is a bit strange because  then it's usage is `text.systemFontSize = 40`, but this will do more than just set the font size, it will override the font family to the system font, which kinda makes sense from the property name, but I think is still strange ;)

**Comment by mossyblog** [comment]
I concur with this. Handing off export capabilities like this typically I'd like to reduce the noise to the basics you visually see in the inspector panel.

**Comment by kgn** [comment]
Seems like there should also be a wrapper class for `Color` as well.

**Comment by kgn** [comment]
Useful discussions on the forum for `Color`: http://sketchplugins.com/d/8-global-colors-gradients
