### ISSUE TITLE
Remove a layer settings by key

### ISSUE THREAD

**Issue by websiddu** [BohemianCoding/SketchAPI#290]
With the current API its not possible to unset a current settings property. Also every the value is convert into a JSON string which mean users have to parse it again.

**Comment by mathieudutour** [comment]
What users are you talking about? The API takes care of stringifying and parsing the value so there shouldn’t be any need for the user to parse anything. 

You can also set the value to `undefined` and you will `undefined` back. 

Or am I misunderstanding something?

**Comment by websiddu** [comment]
Ahh.. Too much UX terminology. User => API Users. 

The API won't accept `undefined` it throws an error like 

`values passed to setValue:forKey:onObject:forPluginIdentifier:: must be composed of arrays, dictionaries, numbers and strings`

About the JSON, I'm talking about the way the content stored `layer.userInfo()[pluginId]` will give result in dictionary but the values need to be parsed. But I think, this is fine as I get loop through keys and use `Settings.layerSettingForKey` to get all values.

**Comment by mathieudutour** [comment]
So which API are you talking about?

`Settings.setSettingForKey(key, undefined)` works fine: https://github.com/BohemianCoding/SketchAPI/blob/develop/Source/settings/__tests__/Settings.test.js#L63-L77

Are you using the `setValue:forKey:onObject:forPluginIdentifier:` API directly?

**Comment by websiddu** [comment]
No I'm not using `setValue:forKey:onObject:forPluginIdentifier:` but it still show this in the log.

**Comment by mathieudutour** [comment]
Ah yes indeed, it only worked for plugin settings, not layer settings.
