### ISSUE TITLE
Using sketch api as Program, not plugin

### ISSUE THREAD

**Issue by softmarshmallow** [BohemianCoding/SketchAPI#291]
I'm trying to make a program
automatically genrates some shape using sketch & sketch plugin,
AFAIK, sketch api seems only available in plugin level.

the plugin program could only be accessed via sketch app.

what i want is something like this.

* ignoring syntex

index.js
```
sketchfile = read("myfile.sketch")
artboards = sketchfile.getAllArtboards()
for ab in artboards:
    ab.saveAsPNG("~/Desktop/imgs")
    
```

and run this script, independently. without building as a plugin

is that possible?

**Comment by bomberstudios** [comment]
Take a look at SketchTool, which is exactly what you want if you only need to export assets: https://developer.sketchapp.com/guides/sketchtool/

**Comment by softmarshmallow** [comment]
@bomberstudios it's more of Study ofComputerVision field.
Need full access of sketch api.
SAD..

Thanks!

**Comment by mathieudutour** [comment]
perhaps if you can explain a bit more your use case we could point you in the right direction? Because as @bomberstudios said, sketchtool is perfect to save artboards as PNGs: https://developer.sketchapp.com/guides/sketchtool/#exporting-artboards

**Comment by softmarshmallow** [comment]
@mathieudutour I'm working on project Analyzing the Sketch Project.
Automatically Labeling Elements, plannig for to use in CV Deeplearing.

Sinario:
read all givven sketch files, get all artboards, create a label to each element. (automatically)

**Comment by mathieudutour** [comment]
So yes, you can use sketchtool to render all artboards to pngs and then use CV to label them.

**Comment by softmarshmallow** [comment]
@bomberstudios No. actually exporting as PNG is not needed.
automatic lableing requires to access sketch layer hierarchy in api level.

And A Ton of other features required. png export support is one of them.

**Comment by softmarshmallow** [comment]
To say it simple.

Use Sketch Api as a library not a framework (want to escape from plugin lifecycle/ecosystem)

**Comment by mathieudutour** [comment]
you can access the sketch layer hierarchy by unzipping a sketch file and looking at the json files inside. 

Using this API outside Sketch is just not possible since it's using the native Sketch obj-c classes

**Comment by robintindale** [comment]
A bit more information - each Sketch file is actually a `zip`  archive containing JSON files. Here's how you would get at that information

* rename a Sketch file from `name.sketch` to `name.zip`
* unzip using an unarchiving utility
* this will give you a structure like this
![image](https://user-images.githubusercontent.com/2700528/48978042-9da26f00-f09d-11e8-9bf9-07a4e53f6f05.png)
* look in `pages` to find the JSON for each page
* the page JSON contains each artboard, where you can find the properties you're after - for example
![image](https://user-images.githubusercontent.com/2700528/48978048-bf9bf180-f09d-11e8-9fb9-cbe4d3726c60.png)

**Comment by softmarshmallow** [comment]
That's Great! Still Api support will be useful for other many developers.
Until then, Parsing JSON is kind of a pain

**Comment by softmarshmallow** [comment]
@robintindale That seems useful. Thanks!

**Comment by softmarshmallow** [comment]
ADDITIONALLY,
Would be also nice to have a Language Level implemented Sketch Json Parser.
or.. is there any?
