### ISSUE TITLE
Add JSON archiving/unarching

### ISSUE THREAD

**Issue by WCByrne** [BohemianCoding/SketchAPI#292]
Any plans to add archiving to the JS API to replace direct access to `MSJSONDataArchiver`? The current toJSON doesn't seem to get everything to recreate the object, example [here](https://sketchplugins.com/d/1127-tojson-couldn-t-get-the-complete-info). 

Maybe this doesn't make sense but for my uses I've wrapped the object in a dict to include the version meta with the object. 
```javascript
{
    "meta": {
        "version": 112
        ...
    },
    object: {
        ...
    }
}
```

**Comment by mathieudutour** [comment]
What's the use case for using `MSJSONDataArchiver`?

**Comment by mathieudutour** [comment]
The thing is that the JSON produced by the archiver might change with every sketch version and the goal of this API is to be stable

**Comment by mathieudutour** [comment]
Yeah, happy to go with something like that if we make it clear that the output is likely to change in the docs.

How about `getSketchJSON` to match `.sketchObject`? I wouldn't mind returning a JSON object, or is there any use case for returning just the string? It seems that everybody will just parse it anyway

**Comment by mathieudutour** [comment]
But tbh, I'm still wondering about the use cases for it 🤔 
The only one I have in mind is having a algorithm that can run on both the JSON file and in a plugin.
My secret plan is to create a nodejs lib that allow to manipulate the JSON file with the same API as this one but that's more long term so it might be worth adding this for now

**Comment by robintindale** [comment]
I guess one use-case is allowing people to access things that aren't in the API yet without need knowledge of the internals - they can get the `sketchJSON` and find what they need. This could be a good way to steer people away from `sketchObject` and needing the headers

Is it actually possible for people to `setSketchJSON`? Obviously could get weird if they give malformed JSON, but would it work to use `JSONUnarchiver` then replace the properties of the existing layer with the new one if the unarchive is successful?

**Comment by mathieudutour** [comment]
it would be possible yes (I think it's `MSJSONDictionaryUnarchiver` that we'd need) but you need to pass a document version to it and that's a pretty big can of worms that I don't really want to open

**Comment by WCByrne** [comment]
My use case is probably not recommended but I'm storing the archive outside the document then unarchiving it to use again later (often in another document). Hence keeping track of the version with each archive. 

Archive doesn't seem like the right term in JS but does it help to think about it more like that? That is, a JSON representation that can be used to recreate this object later.

**Comment by WCByrne** [comment]
My use case is probably not recommended but I'm storing the archive outside the document then unarchiving it to use again later (often in another document). Hence keeping track of the version with each archive. 

Archive doesn't seem like the right term in JS but does it help to think about it more like that? That is, a JSON representation that can be used to recreate this object later.

**Comment by WCByrne** [comment]
Happy to tackle this. Do you have a direction in mind @mathieudutour? Regarding unarchiving in particular since it is little less trivial? The options that come to mind are:
1. No **un**archiving - less ideal
2. Embed the version in the archive so the process is self contained and developer doesn't need to understand the concept of versioning at all (example above)
3. Allow unarchiving with a provided version - defaults to current version

**Comment by mathieudutour** [comment]
I'd say 3 and I'll put the version in `process.versions.document`. Then you can build another object with it if you need to store it.

What do you think @robintindale?

**Comment by robintindale** [comment]
yeah I think 3 is the best option.

I think it would be OK to document it with a sufficiently large and loud warning, basically saying "use at your own peril", no help guaranteed etc.
