### ISSUE TITLE
Crash when logging "context" in console

### ISSUE THREAD

**Issue by paintedbicycle** [BohemianCoding/SketchAPI#293]
Hello,

I've found that if you're using Sketch Dev Tools and you have the console open, Sketch will crash when logging the "context" object of a data supplier plugin.

console.log(context) // This crashes
console.log(context.data) // This does not crash

Paul

**Comment by detj** [comment]
Tried this on Sketch 52.5. Doesn't seem to crash now.

**Comment by paintedbicycle** [comment]
@detj did you have the dev tools console open?

I just tried on 52.5 and it still crashes for me.

**Comment by detj** [comment]
> @detj did you have the dev tools console open?
yes

**Comment by mathieudutour** [comment]
I think I found the bug, should be fixed in the next release
