### ISSUE TITLE
Possible to get name or identifier of menu item in function?

### ISSUE THREAD

**Issue by paintedbicycle** [BohemianCoding/SketchAPI#294]
I'm adding a menu to my data supplier plugin and I have a need to find out _which menu item_ the user selected. Is this possible? I've tried logging the info I can get but because of https://github.com/BohemianCoding/SketchAPI/issues/293 I'm not sure I'm seeing all data available to me.

I want to call the same handler with multiple menu items, but know which menu item identifier (or any other identifying information from the menu item) called it.

Currently, you create a menu item that references a command identifier:

`manifest.json`
```
  "menu": {
    "title": "Change Address",
    "items": [
              "rename-layer", // Command identifier
            ]
     },
```

The command identifier then references a script and a handler function in it.

`manifest.json`
```
  "commands": [
    {
      "name": "Address",
      "identifier": "rename-layer", // Command identifier
      "handler": "onChangeLayerName", // Function I want to call with multiple commands
      "script": "commands/address.js"
    }
  ],
```

Now, inside that handler function, is it possible to get which command identifier triggered it?

If not, I'd have to create a unique function for every single command. I've looked in the source code of several plugins with big menus (like "Content Generator") and it does indeed seem like this is the route they went.

It seems like a lot of boilerplate. Potentially up to 130 extremely similar functions in my case. I'd like to just create one function and use logic to determine what I want the function to do.

Thanks,

Paul

**Comment by mathieudutour** [comment]
I think `String(__command.identifier())` will give you what you want. I'm thinking about adding a polyfill for `process` and putting `process.pid` to the identifier. What do you think?

**Comment by paintedbicycle** [comment]
Hey @mathieudutour, yes `String(__command.identifier())` seems to be what I need. Thanks for that.

As for `process` - are you asking where I'd prefer to access the `identifier`? 
- To to be honest I didn't even know about `process`. Maybe it needs more documentation.
- Does something like `context.menu.identifier` make sense? Seems more intuitive as `process` seems to be more about the environment.

Paul

**Comment by mathieudutour** [comment]
well it doesn't exist yet but I want to aim for a more nodejs environment and `process` is a big part of it. I kind of want to get rid of `context` because it's a native object which doesn't play well with javascript.

> Does something like context.menu.identifier make sense?

I think it's already in `context.command.identifier()` if you prefer to use `context`

**Comment by paintedbicycle** [comment]
Got it. Well it feels to me that I haven't dug in deeply enough to help. It seems like you have some deep thinking going on here.

I would just say that:
- I'd expect stuff about the environment / system (nodejs, browser, config variables, etc) in one spot by itself and likely used only in a small percentage of edge cases
- I'd expect stuff about the Sketch document and layers in a different spot than the environment stuff (like it is)
- I _think_ I'd expect the user interaction stuff to be in a different spot again, but I'd understand if it was with the document.

It feels like this is what you're doing generally. I think perhaps I was just confused by the terminology of `process`,  `command` and `context` and I didn't come across documentation for some of it so didn't know it before asking.

Thanks for all your help,

Paul

**Comment by mathieudutour** [comment]
That's pretty much what I want to do yes:

- environment/system -> `process` global variable
- DOM -> `require('sketch')`
- UI -> `require('sketch/ui')`

The `context` should just be about accessing the arguments of the handler (eg. the number of items asked for a data supplier handler for example) and not the environment

**Comment by paintedbicycle** [comment]
Cool. Just feels "user interaction" is an outlier.

Basically you can get the selection (selected layers) which feels like a user interaction in one place, but the menu item they clicked in a different one.
