### ISSUE TITLE
Add a jQuery style selection method

### ISSUE THREAD

**Issue by mathieudutour** [BohemianCoding/SketchAPI#310]
Right now it’s pretty inefficient to find all the text layers in a page. We already have an efficient method to find a layer by its name but rather than stopping at adding specific methods for each use case, I’d rather think of a more generic solution.

So something like a jQuery method makes sense to me:
```js
// returns an array of text layers in the selected document
sketch.$(`${sketch.Types.Text}`)

// returns all the layers in the page
sketch.$(‘*’, page)

// returns an array of layers whose name contains “special-name”
sketch.$(`[name*="special-name"]`)

// shortcut for the id
sketch.$(`#${id}`, page)

// shortcut for boolean properties
sketch.$(`:locked`)
sketch.$(`:not-locked`)
```

That selector string will need to parsed and translated to an NSPredicate for the search to be efficient.

**Comment by robintindale** [comment]
Oo, yeah we discussed this last year. See https://sketchplugins.com/d/464-feedback-wanted-javascript-api/26 for previous discussions

I think it still sounds promising - syntax can start super basic and gradually add more advanced stuff. I'd say a simple method name like `find` would be more descriptive.

Would it return a bundled array like jQuery, so you can call methods on it? I guess that could be hard to wire up right, so it would be ok if you had to call `each`

Might be good to discuss whether GraphQL is appropriate too, that seems to be the trendy way nowadays of providing this sort of access. I know you did an experimental access mechanism https://github.com/mathieudutour/graphql-x-sketch
