### ISSUE TITLE
Getting the kerning of a font after it has been set in the UI returns a value that is slightly different than what was set.

### ISSUE THREAD

**Issue by KevinGutowski** [BohemianCoding/SketchAPI#319]
Steps to reproduce:

1. Create a text object
2. Increase the character spacing in the sketch UI
3. Read the kerning of the text object via the API

```
// Text object is created and character spacing is set to 0.6 from the sketch interface
const document = require("sketch").getSelectedDocument();
const textLayer = document.selectedLayers.layers[0];

textLayer.style.kerning
// is 0.6000000238418579
// expected is 0.6
```

**Comment by KevinGutowski** [comment]
I was doing a bit more testing with this and it seems like `0.5` returns back `0.5` but other values don't seem to.

**Comment by mathieudutour** [comment]
Ah floating point numbers... Indeed, `0.5` can be represented precisely but most decimal numbers can't. I guess I could round it up before returning it in the API
