### ISSUE TITLE
CocoaScript API for querying and changing the starting point of a vector line

### ISSUE THREAD

**Issue by justin-calleja** [BohemianCoding/SketchAPI#329]
I tried looking into implementing a plugin for the issue brought up in the video in this blog post: [https://medium.com/sketch-app/what-s-up-with-sketch-s-scissors-tool-ebdf4d57276f](https://medium.com/sketch-app/what-s-up-with-sketch-s-scissors-tool-ebdf4d57276f)

(video: https://player.vimeo.com/video/127117419)

Basically: a plugin to change the starting point of a vector line.

I'm new to Sketch plugin development. I could not find a way to query for the currently selected point of a vector here: [https://developer.sketchapp.com/reference/api/](https://developer.sketchapp.com/reference/api/)

Can API calls be added for this? (Also, the plugin would require other calls to set the starting point).

Thanks

**Comment by mathieudutour** [comment]
That will be fixed by https://github.com/BohemianCoding/SketchAPI/pull/304. You will be able to get the starting point and modify it like this:
```
line.points[0]
```
