### ISSUE TITLE
selection change does not declare a run handler.

### ISSUE THREAD

**Issue by mdonogma** [BohemianCoding/SketchAPI#333]
scripts for selection change does not work

followed it exactly per readme.

error when trying to run 

Error in command Selection Changed Script at path /Users/michaelmcdonogh/Documents/selection-changed/plugin.sketchplugin/Contents/Sketch/selection-changed.js does not declare a run handler.

this is a frustrating experience. please provide working examples for developers to your api's

**Comment by mathieudutour** [comment]
Just don't run `npm run start`. Build the plugin and then select a layer. A message should show up

**Comment by mdonogma** [comment]
Thx

**Comment by NickolasBoyer** [comment]
I would be very nice if this could be indicated somewhere, even the example doesn't "work" properly if you don't know this.

**Comment by robintindale** [comment]
maybe the example should define a default run handler which displays a message explaining that you need to select a layer to see the behavior

**Comment by robintindale** [comment]
Ah I see Mathieu also removed `npm run start` from the page  in bdf077b5d000147e4a5010065fb05a9f4de2dbd1

**Comment by mathieudutour** [comment]
Yeah that's something that should be fixed in skpm directly: https://github.com/skpm/skpm/issues/113
