### ISSUE TITLE
auto install plugin (without the prompts) after npm run build

### ISSUE THREAD

**Issue by mdonogma** [BohemianCoding/SketchAPI#338]
is there a way to auto install plugin after npm run build without the two prompts & without restart of sketch.

![image](https://user-images.githubusercontent.com/13458476/51018805-a0f9a780-15c4-11e9-8359-a03dff51b339.png)

do this 100's and it will start driving you bonkers (Each change requires reinstall of plugin)

**Comment by mathieudutour** [comment]
Are you using skpm? Then it should be automated already: the plugin is symlinked so you don't have to reinstall it.

But I'd recommend you to read https://developer.sketchapp.com/guides/preferences/#always-reload-scripts-before-running
