### ISSUE TITLE
Add ability to import files

### ISSUE THREAD

**Issue by WCByrne** [BohemianCoding/SketchAPI#366]
When pasting vector graphic files into Sketch they are converted to native layers. It would be great if to be able to tap into this programmatically via the API.

Perhaps this could be in the form of a method to import any importable file. It could handle pdfs, svgs, bitmap and returns the layers. Something along the lines of:
```javascript
function layersFromFileData(data) -> Layer
```

**Comment by WCByrne** [comment]
If anyone can shed some light on the internals for accomplishing this I would be happy to work on the API implementation. 

The best I've come across so far is from this [forum post](https://sketchplugins.com/d/267-import-svg/14) which has this code snippet:
```javascript
var svgString = NSString.stringWithString('<svg width="200px" height="100px" viewBox="0 0 200 100" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><rect fill="#000000" x="0" y="0" width="200" height="100"></rect></svg>');
var svgData = svgString.dataUsingEncoding(NSUTF8StringEncoding);
var svgImporter = MSSVGImporter.svgImporter();
svgImporter.prepareToImportFromData(svgData);
var svgLayer = svgImporter.importAsLayer();
svgLayer.setName("LayerName");
context.document.currentPage().addLayers([svgLayer]);
```

I haven't come across anything for PDFs yet.

**Comment by mathieudutour** [comment]
instead of `MSSVGImporter.svgImporter()`, you have `MSPDFImporter.pdfImporter()` or `MSPDFImporter.epsImporter()`. The rest of the API is the same
