### ISSUE TITLE
Allow duplication without a parent

### ISSUE THREAD

**Issue by WCByrne** [BohemianCoding/SketchAPI#376]
The [code for duplicating a layer](https://github.com/BohemianCoding/SketchAPI/blob/27d0f779a18b1d8689e3933e927bd199e2e21bbb/Source/dom/layers/Layer.js#L20) only works if the initial layer has a parent. Why not allow copying the layer without a parent?

**Comment by mathieudutour** [comment]
I guess there is no reason haha
