### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by marvinhagemeister** [BohemianCoding/SketchAPI#38]
`sketch-api` is not yet available on npm.

**Comment by mathieudutour** [comment]
There are no actual benefits to publish it on npm, is it? The nice things about the api is that it's bundled in sketch so we don't need to care about handling the different versions of sketch (or update it when we update sketch). If we start to publish it on npm, people will start to bundle it themselves and it will break.

I've created an empty package to park it on npm tho, we never know ;)
