### ISSUE TITLE
Expose Asset id

### ISSUE THREAD

**Issue by WCByrne** [BohemianCoding/SketchAPI#381]
I'm not really sure why [Asset](https://github.com/BohemianCoding/SketchAPI/blob/c8609b6180657e59bc48a139d6a4b8ec1f1ef45e/Source/dom/assets/Asset.js#L5) needs to remove the `id` property. `MSColorAsset` and related classes have an `objectID`. Would it be problematic to expose it?

**Comment by mathieudutour** [comment]
because the id doesn't mean anything and isn't used by sketch so exposing will give bad ideas to people
