### ISSUE TITLE
getSelectedDocument returns wrong document when there are multiple files open

### ISSUE THREAD

**Issue by ryenbeatty** [BohemianCoding/SketchAPI#384]
Hi there,

I have noticed in Sketch 53.1 that the Document.getSelectedDocument() seems to bind itself to the first document that opens, and from then on the value does not update when switching to other documents.

You can reproduce this by creating 2+ sketch files, and logging out the Document.getSelectedDocument().path whenever you switch between them. You will see that it doesn't update.

Any suggestions to help workaround or solve this issue?
Thanks!

**Comment by ryenbeatty** [comment]
I should also mention that I tried the alternative method of accessing the current document from #253, but it did not seem to help.

**Comment by mathieudutour** [comment]
So is there an issue?

**Comment by ryenbeatty** [comment]
Looks like the issue was that my Document.getSelectedDocument call was nested inside a sketch-module-webview win.on('focus') callback, which I setup 'onOpenDocument', so I need a way to update this webview whenever I switch documents as well. So I don't think there is an underlying issue.
