### ISSUE TITLE
SymbolInstance.master throws error when wrapping MSImmutableSymbolInstance

### ISSUE THREAD

**Issue by andrewstart** [BohemianCoding/SketchAPI#389]
The base problem isn't really a Sketch API issue, but in Sketch 53.1, a SymbolInstance object wrapping an MSImmutableSymbolInstance (for example, accessed from the document in the ExportSlices action) throws the following error when attempting to read the `master` property:
```
TypeError: this._object.symbolMaster is not a function. (In 'this._object.symbolMaster()', 'this._object.symbolMaster' is undefined)
```
I had a similar issue in Sketch 52 with Text layers (MSImmutableTextLayer didn't implement everything), and for this had to update my workaround that ensured that I got a mutable version of the current document - currently using `NSDocumentController.sharedDocumentController().currentDocument()`

**Comment by mathieudutour** [comment]
Thanks for the report!

For the moment you can workaround the same way you did with the Text Layer: get the document and then use `document.getSymbolMasterWithID(symbolInstance.symbolId)`

**Comment by mathieudutour** [comment]
Do you remember what was the issue fot the Text Layer?

**Comment by andrewstart** [comment]
It looks like MSImmutableTextLayer didn't implement `verticalAlignment()`, which is moot now that the property has moved to the style object in the JS API (and works for mutable and immutable documents).

I found another bug to add to the "immutable objects aren't the same as mutable ones" list - while investigating this, I did discover that when Document wraps MSImmutableDocumentData, `console.log()` fails when attempting to log `myDoc.pages`:
```
TypeError: this._object.documentData is not a function. (In 'this._object.documentData()', 'this._object.documentData' is undefined)
line: 1
sourceURL: /Applications/Sketch.app/Contents/Resources/SketchAPI_dom.js
column: 93903
stack: get@/Applications/Sketch.app/Contents/Resources/SketchAPI_dom.js:1:93903
/Applications/Sketch.app/Contents/Resources/core-modules/@skpm/util/index.js:341:22
forEach@[native code]
formatValue@/Applications/Sketch.app/Contents/Resources/core-modules/@skpm/util/index.js:337:38
formatProperty@/Applications/Sketch.app/Contents/Resources/core-modules/@skpm/util/index.js:585:22
formatArray@/Applications/Sketch.app/Contents/Resources/core-modules/@skpm/util/index.js:563:31
formatValue@/Applications/Sketch.app/Contents/Resources/core-modules/@skpm/util/index.js:423:25
inspect@/Applications/Sketch.app/Contents/Resources/core-modules/@skpm/util/index.js:192:21
format@/Applications/Sketch.app/Contents/Resources/core-modules/@skpm/util/index.js:92:19
logEverywhere@/Applications/Sketch.app/Contents/Resources/core-modules/@skpm/console/index.js:19:38
log@/Applications/Sketch.app/Contents/Resources/core-modules/@skpm/console/index.js:130:25
```
This error is not thrown when Document wraps an MSDocument, although it is an array of NSNull objects as far as `log()` is concerned regardless of what Document wraps.
