### ISSUE TITLE
Add selectedOverrides property

### ISSUE THREAD

**Issue by mathieudutour** [BohemianCoding/SketchAPI#392]
https://sketchplugins.com/d/1255-sketch-53-get-value-of-override-selected-in-layer-list

**Comment by w312011343** [comment]
I want to get the size and position of the selectedOverride element，But when I split selectedOverrides, iterate over the get element ,I can't get the elements I want(Target elements nested in multiple groups).I also see other ways to get the elements(selection[0].override[0].affectedLayer),But the size and position of the elements obtained by this method are very different from the actual values.How to get the display frame of the selectedOverride element？thx
