### ISSUE TITLE
Getting access to named colors in palettes

### ISSUE THREAD

**Issue by custa1200** [BohemianCoding/SketchAPI#397]
Hi, I starting to use the Amazing Style Dictionary project for design tokens which would allow the generation of Sketch palettes. The devs would like to know any information around what it would take to write them out but I could see nothing in the API documentation here about the naming of colors. Could you please clarify, I'll link this issue over to where I asked about it on their board.

**Comment by mathieudutour** [comment]
In Sketch 53.1, there are a `document.colors` and `document.gradients` properties: https://github.com/BohemianCoding/SketchAPI/blob/develop/docs/api/Document.md

And in Sketch 54, there will be `sketch.globaleAssets.colors` and `sketch.globalAssets.gradients`.

The docs will be updated as soon as 54 is released
