### ISSUE TITLE
Piping Sketch Events To API

### ISSUE THREAD

**Issue by AdrianHigginsDev** [BohemianCoding/SketchAPI#410]
I am incredibly sorry if I missed something where this is already possible, but;

For those of us using the BrowserWindow plugin (Electron for Sketch), we have a lot of dependencies related to the "on-window-close" event.

However if someone closes sketch (which will close the window), we cannot catch this event, which for me is causing a serious conflict.

If there was a way for you to pipe your own on-window-close (that's bound to Sketch.app) that we can use for an event listener, it would be really useful.

If this already exists, I apologize and will close the issue.

**Comment by mathieudutour** [comment]
you should be able to add a listener to the [Shutdown](https://developer.sketchapp.com/reference/action/Shutdown/) action and do your clean up here. But keep in mind that it might not always be called if Sketch is forced quit or something.
