### ISSUE TITLE
 the selectedOverrides element size and position is wrong

### ISSUE THREAD

**Issue by w312011343** [BohemianCoding/SketchAPI#412]
I get the selected element in selectedOverrides by traversing overrides(override[i].affectedLayer), but when I get the size and the position of this element, it is very different from the one shown in symbolInstance.

[question](https://sketchplugins.com/d/1291-how-to-get-the-width-and-height-of-the-selectedoverrides-element)

**Comment by mathieudutour** [comment]
It's because `affectedLayer` reference the original layer, not the position of the override.

In Sketch 54 you will have a new method `override.getFrame()` to get its position
