### ISSUE TITLE
Show a proper object for the Selection Object

### ISSUE THREAD

**Issue by KevinGutowski** [BohemianCoding/SketchAPI#417]
![Screen Shot 2019-03-19 at 4 39 18 PM](https://user-images.githubusercontent.com/4199296/54648988-91d02380-4a65-11e9-9574-4cd4f9a62a51.png)

I have an artboard and some layers. If I select the containing artboard I get a strange object back from `document.selectedLayers`.

```
{ _object: <MSPage: 0x7fd0c4224e10> }
```

I then have to some special wrapping of this `sketch.fromNative(layer._object)` which seems brittle. I was expecting `document.selectedLayers` to return a wrapped layer object. In other words, I thought that `page.layers[0]` should be the equivalent of `layer`

**Comment by mathieudutour** [comment]
`document.selectedLayers` is a Selection object: https://developer.sketchapp.com/reference/api/#selection. It is not a layer nor an array of layers.

**Comment by mathieudutour** [comment]
In hindsight, I guess `selectedLayers` would have been better named `selection` but well...

**Comment by KevinGutowski** [comment]
Hmm... thinking about this a bit more, I guess I am a little confused why the selection object isn’t formatted like this when logged:

```
{
    layers: [Array],
    length: Int,
    isEmpty: Boolean
}
```

Currently it returns something that isn’t quite helpful in understanding what the supported methods are
```
{ _object: <MSPage: 0x7f9f665d6cf0> }
```

Just kinda have to memorize (or look at the docs) to know what methods are available. From the perspective of a new developer, The `Layer` object and its instances are a bit easier to work with because you can just log them and see all the properties.

**Comment by mathieudutour** [comment]
Ah that makes sense. I can probably fix that
