### ISSUE TITLE
How to get a remote document?

### ISSUE THREAD

**Issue by DrinkingWords** [BohemianCoding/SketchAPI#418]

**Comment by DrinkingWords** [comment]
How to get a remote document?

**Comment by mathieudutour** [comment]
What do you mean by remote document?

**Comment by DrinkingWords** [comment]
When a sketch document is on the server, is there any way to add a layer to the document?
I try to open a sketch document on the server by the method below and I got an error.
Document.open('http://127.0.0.1:9999/ccc.sketch', (err, document) => {})
I can get a remote library from an RSS feed URL by method getRemoteLibraryWithRSS, but I can not add a layer to the library’s document.

**Comment by DrinkingWords** [comment]
How to remove a local shared style?

**Comment by mathieudutour** [comment]
> When a sketch document is on the server, is there any way to add a shared style to the document?

No, you will need to:
- download the sketch document
- open it
- make your change
- update the RSS feed
- upload the changed document and the new rss feed

> How to remove a local shared style?

`document.sharedTextStyles = document.sharedTextStyles.filter(sharedStyle => {
  return sharedStyle.id !== SHARED_STYLE_ID_TO_REMOVE
})
