### ISSUE TITLE
Setting a selection doesn’t refresh the canvas

### ISSUE THREAD

**Issue by KevinGutowski** [BohemianCoding/SketchAPI#428]
```
var sketch = require('sketch')
var ShapePath = sketch.ShapePath
var Rectangle = sketch.Rectangle
var Style = sketch.Style
var document = sketch.getSelectedDocument()
var page = document.selectedPage

page.layers = []

let rectangle = new ShapePath({
  name: "my shape",
  frame: new Rectangle(0,0,100,100),
  style: { 
    fills: [{ 
      fill: Style.FillType.Color,
      color: '#000'  
    }]
  },
  parent: page
})

let rectangle2 = rectangle.duplicate()
rectangle2.frame.offset(110,0)

rectangle.selected = true

document.sketchObject.reloadInspector()
```

I create two rectangles and select the first one. If you rerun the script but then change `rectangle.selected = false` then the canvas doesn’t properly remove the resize handles. Seems like I need to do something similar to `document.sketchObject.reloadInspector()` but with the canvas.

<img width="497" alt="Screen Shot 2019-03-25 at 12 55 11 AM" src="https://user-images.githubusercontent.com/4199296/54903230-a9aa0c00-4e98-11e9-86b3-a19fb974cb6d.png">
You can see no layers are selected however the first layer still has the resize handles.

**Comment by KevinGutowski** [comment]
I thought it was something time related and tried

```
rectangle.selected = true
setTimeout(function(){ rectangle.selected = false }, 400)
```

But that seems to do the right thing which means the issue is something to do with the multiple script runs.

**Comment by mathieudutour** [comment]
I don't think there is anything wrong: when you re-run the script, you create 2 new rectangles on top of the old ones. But the old one is still selected. The resize handles that you see are from the first rectangle

**Comment by KevinGutowski** [comment]
Ah yeah, that seems to be the issue. If I put `document.selectedlayers.layers = []` and clear out the selection before starting it does the expected behavior. Thanks!
