### ISSUE TITLE
Unable to get `console.clear` working

### ISSUE THREAD

**Issue by KevinGutowski** [BohemianCoding/SketchAPI#433]
Steps to reproduce

1. Open Sketch DevTools
2. Open Plugins -> Run Script
3. Type 
```
console.log("hi")
console.clear
```
4. Run the script twice
5. See that "hi" is reported twice in the DevTools console.

**Comment by mathieudutour** [comment]
so `console.clear` is a function, so it should be `console.clear()`. But you are right, it's not clearing yet. Should be in the next beta

**Comment by KevinGutowski** [comment]
Ah oops! Forgot to call the function. Yeah exactly.
