### ISSUE TITLE
Add support for document colors

### ISSUE THREAD

**Issue by kgn** [BohemianCoding/SketchAPI#44]
Both colors and gradients

Proposal:

Application.globalColors - get/set
Application.globalGradients - get/set

**Comment by kgn** [comment]
I think with this it would be good to have a wrapper class for `Color` that's used with these.

**Comment by WCByrne** [comment]
Any plans for this one? I can take a stab at it

I was curious if there were any plans to add IDs to document colors to make it possible to reference them but considering the JS API is only representing colors as hex values I'm guessing that is a no. @mathieudutour would you expect access to the document colors to be the same or something more robust/flexible?

**Comment by mathieudutour** [comment]
We do have some plans regarding document's and global colors, that's why I was waiting a bit it before adding something to the API.

> I was curious if there were any plans to add IDs to document colors to make it possible to reference them
That would be a change in Sketch so we can't just add it in the API.

So I was thinking about having:
```
sketch.globalColors = [
 {
    color: Color,
    // we might add some stuff there later
  }
]
sketch.globalGradients = [
  {
    gradient: Gradient,
    // we might add some stuff there later
  }
]

document.colors = [...]
document.gradients = [...]
```

What do you think?

**Comment by WCByrne** [comment]
The API makes sense to me.  I assume `Color` is a color object? If so, could the list just be `[Color]`/`Gradient`? It's not clear what "some stuff" would be, extra color information or something specific to the color in the list?

Let me know if I can help.

**Comment by mathieudutour** [comment]
`Color` would indeed be that object: https://github.com/BohemianCoding/SketchAPI/blob/develop/Source/dom/style/Color.js and `Gradient` that one: https://github.com/BohemianCoding/SketchAPI/blob/develop/Source/dom/style/Gradient.js.

The extra information might be an id or a name for example. Once again, that's not something that is currently implemented in Sketch so we just have to be careful here not to introduce breaking changes in the future.

**Comment by WCByrne** [comment]
👍 Got it. I didn't see that class there.

Probably makes the most sense to figure out how the internals will work before getting too far into it. i.e will the document colors be a sort of SharedColor object like SharedStyles are? Any timeline for that yet?

**Comment by WCByrne** [comment]
In light of a breaking change with the internal API here it would be nice to push this forward. 

Regarding the extra information, is there a reason that info would need to go in an object around the color rather than directly on the color object itself?

**Comment by mathieudutour** [comment]
So actually let’s do it like this:
```js 
sketch.globalColors = [
 {
    name: string,
    color: string, // rgba string (colorToString(nativeColor))
  }
]
```

**Comment by WCByrne** [comment]
Are you opposed to exposing the Color object and fleshing it out? I was actually making use of color model conversions from MSColor/NSColor that seem like they could be useful to other plugins (i.e. rgb & hsb). Not too mad to replace manually but it's nice to know that it's being done the same way and will match the internal values; Though, I assume it is using NSColor under the hood somewhere???

Could you clarify the new 53 internals? It looks like .assets().colorAssets() is now a list of MSColorAsset objects, I'm a little unclear on the hierarchy from there without class dump; I assume there is an MSColor on there somewhere 🤔

**Comment by WCByrne** [comment]
Also, what about editing the document colors, a replacement for `docData.assets().addColor(msColor)`?

**Comment by mathieudutour** [comment]
Not really keen to expose the Color object, I’d rather have people use a js lib rather than falling back to the obj-c API. IIRC, when you set a color, you can set it to an MSColor (or NSColor) and under the hood `Color.from()` will take care of it.

An `MSColorAsset` has a `color` and `name` property.

I don’t think we need a method to add a color: `document.colors.push({ color, name })` is enough

**Comment by WCByrne** [comment]
Perfect, I could have sworn `MSColorAsset.color` wasn't working when I tried the first time 🤦‍♂️. 

Last pieces to find from the internal API - asking for my own use and also so it's documented for this issue:
1. Add a document color
2. Is it possible to update a color (or at least it's name as you can do in the UX)? If so, internal API?

---

Regarding the Color object: Seems to me a bit unfortunate to require plugin devs to find and use an external library (or custom code) just to inspect the numeric values of a color. Colors seem like a pretty important part of any Sketch document but I suppose simply displaying the hex is probably the most common use for plugins.

**Comment by WCByrne** [comment]
And creating an `MSColorAsset` with a color? I tried class dump but couldn't find anything about `MSColorAsset` 😞. Just want to make sure I'm finding the right APIs.

**Comment by mathieudutour** [comment]
No you are right it doesn't work out of the box. I fixed it here: #314 so we can do the same thing for the colors

**Comment by WCByrne** [comment]
Perfect, that's what I was missing 👍.

Last question on this hopefully: What is the API for global asset collections? Assuming the container object is the same, where is it stored, i.e. the equivalent of `document.assets` for global assets?

**Comment by WCByrne** [comment]
☝️ Merged. Looks like this can be closed.
