### ISSUE TITLE
check if a point is selected when editing a path

### ISSUE THREAD

**Issue by DrinkingWords** [BohemianCoding/SketchAPI#441]
I want to set cornerRadius to a corner of a rectangle, so how can I get the selected corner?

**Comment by mathieudutour** [comment]
So right now there is no way to get the selected point using the API, it will be available in Sketch 55.

You can change the cornerRadius of a point with:
```js
shape.points[0].cornerRadius = 5
```

see https://developer.sketch.com/reference/api/#curvepoint
