### ISSUE TITLE
Its a little hard to know what commit of the release/54 branch gets added to Sketch Beta realeases

### ISSUE THREAD

**Issue by KevinGutowski** [BohemianCoding/SketchAPI#442]
I’m looking through the commits of https://github.com/BohemianCoding/SketchAPI/commits/release/54 and am trying to figure what changes were added with Sketch 54 Beta 2. Do you have any suggestions where I might be able to look to see a diff between Beta 2 and Beta 1?

**Comment by mathieudutour** [comment]
I'm not sure when Beta 2 was released 🙈

**Comment by mathieudutour** [comment]
I'd say maybe "Merge pull request #423 from BohemianCoding/feature/23989"?

**Comment by KevinGutowski** [comment]
Oops forgot to reply here! I'll just take a guess at what changed between beta releases :D
