### ISSUE TITLE
libraryID does not ensure uniqueness

### ISSUE THREAD

**Issue by 1leprechaun** [BohemianCoding/SketchAPI#443]
I'm using symbols from 2 different libraries, one of them being 'User' type, and the other one 'Internal'. The problem is that both of them have the same libraryID, thus being impossible to manage them(identification by name couldn't be an option).
That happens with only a specific 'User' library, any other libraries don't have this issue.

Is there another option to uniquely identify and manage libraries?
Below I posted a screenshot of the JSON dumped by sketchtool. 
 
<img width="431" alt="Screenshot 2019-03-29 at 15 29 12" src="https://user-images.githubusercontent.com/46530169/55244125-39f5a180-5249-11e9-9d00-b6695d06c8a8.png">

Thank you!

**Comment by mathieudutour** [comment]
we use a combinaison of libraryId and library name. The libraryId is the documentId of the library so if you copy paste the document and add it as a library, you will have multiple libraries with the same id.
