### ISSUE TITLE
What is an easy way to test that you have successfully changed your API location?

### ISSUE THREAD

**Issue by KevinGutowski** [BohemianCoding/SketchAPI#452]
I can’t seem to get my instance of Sketch Beta pointing to my local version of the API. Here is what I did:

```
npm install --no-shrinkwrap
```

```
npm start
```

```
defaults write com.bohemaincoding.sketch3.beta SketchAPILocation "/Users/Kski/Dev/myProjects/SketchAPI/build/SketchAPI.js"
```

Is there a way to check in the scripting panel that it is being loaded from the right directory?

Also,

```
defaults read com.bohemaincoding.sketch3.beta SketchAPILocation
```

returns back the expected path :/

**Comment by mathieudutour** [comment]
hum, you can change the version of the API in `Source/dom/index.js` and run `console.log(require('sketch').version)`?

**Comment by KevinGutowski** [comment]
Darn, its still not working for me :/ I'll make a little video of the steps that I am doing later tonight. I'm probably doing something dumb.

**Comment by KevinGutowski** [comment]
Here is a little video of me trying to get it to work! Hope it helps https://youtu.be/kkEVfDr_PHw

**Comment by KevinGutowski** [comment]
Hmm I actually think something is wrong with the build because I can see in the compiled output that the api is still "2.0.0"

![Screen Shot 2019-04-08 at 9 59 59 PM](https://user-images.githubusercontent.com/4199296/55774412-dc800280-5a49-11e9-8ef0-c85337cf615e.png)

**Comment by mathieudutour** [comment]
Hum the version appears multiple times (one for each bundle), so it might be one that you haven't change (is there `3.0.0` in the compiled file?).

@WCByrne I think you managed to get it working? Do you see anything out of order here?

**Comment by WCByrne** [comment]
@mathieudutour Well, normally it just works but I just checked out develop and I am getting this in the run script panel with a single line: `require('sketch')`
```
Error: An Obj-C exception occurred.
line: 2
nativeException: *** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: ****/SketchAPI/SketchAPI.js)
column: 31
```

**Comment by KevinGutowski** [comment]
Darn, I’m still having no luck :( I did find the number api number change in the compiled file. (Here I changed it to `5.2.0`)

![Screen Shot 2019-04-12 at 10 57 30 PM](https://user-images.githubusercontent.com/4199296/56075369-6abff580-5d76-11e9-80cf-ebd2b1608599.png)

**Comment by mathieudutour** [comment]
Spent way too much time finding that it should be `com.bohemiancoding.sketch3.beta` and not `com.bohemaincoding.sketch3.beta` haha

**Comment by KevinGutowski** [comment]
Ooo damnnn my bad 😅 I'll try it out tonight

**Comment by KevinGutowski** [comment]
Grrr… its still not working for me 😭

**Comment by mathieudutour** [comment]
Steps I did which work for me:
- `defaults write com.bohemiancoding.sketch3 SketchAPILocation /Users/mathieudutour/Desktop/SketchAPI.js`
- change `MSApplicationMetadata.metadata().appVersion` to `'test'` in `Source/dom/index.js`
- `npm run build`
- copy paste the `sketchAPI.js` on my desktop
- start sketch (important to restart sketch after setting the api location)
- run `console.log(require('sketch').version)`
- output is `{ sketch: 'test', api: '2.0.0' }` as expected

**Comment by WCByrne** [comment]
FWIW I've added a script to package.json in my copy of the API for easily enabling/disabling the API. 
```
"enable:beta": "defaults write com.bohemaincoding.sketch3.beta SketchAPILocation \"$PWD/build/SketchAPI.js\""
```

**Comment by KevinGutowski** [comment]
WOO so I followed those steps exactly and it works! 💃 I'm not really sure what I did differently (other than moving the `sketchAPI.js` to the desktop and changing the location accordingly). But I'm so happy that it works now. Thanks so much for all your patience. 🤩

**Comment by KevinGutowski** [comment]
Sooo I think the issue has to do with my home computer…. cause I was able to get my work computer working just fine over lunch today. Is there anything that I can do just to do a clean install of sketch? Like completely wipe all dependencies? Gah so frustrating 🥺 I’m out of ideas.

**Comment by KevinGutowski** [comment]
Did a little bit more digging trying to figure out where the plist files are located. 

I first deleted the SketchAPILocation from both the beta and regular versions of Sketch
`defaults delete com.bohemiancoding.sketch3 SketchAPILocation`
`defaults delete com.bohemiancoding.sketch3.beta SketchAPILocation`

When I attempted to read them I got some interesting output
```
 defaults read com.bohemiancoding.sketch3 SketchAPILocation
// 2019-04-24 00:00:27.298 defaults[2410:31759]
// The domain/default pair of (com.bohemiancoding.sketch3, SketchAPILocation) does not exist
```
```
defaults read com.bohemiancoding.sketch3.beta SketchAPILocation
// 2019-04-24 00:00:22.413 defaults[2403:31492]
// The domain/default pair of (/Users/Kski/Library/Containers/com.bohemiancoding.sketch3.beta/Data/Library/Preferences/com.bohemiancoding.sketch3.beta, SketchAPILocation) does not exist
```

For some reason my beta version’s api location is different 🤔

I went and edited the plist file from the usual plist location (`/Users/Kski/Library/Preferences/com.bohemiancoding.sketch3.beta.plist`) and that seemed to do the trick…

![Screen Shot 2019-04-24 at 12 11 10 AM](https://user-images.githubusercontent.com/4199296/56639411-7be5ed80-6625-11e9-9621-de68bd1838be.png)
(Yay my custom sketch name came through)

So I dunno how I can fix the `defaults {command} com.bohemiancoding.sketch3.beta` to point to the right location.

**Comment by mathieudutour** [comment]
Oh that's interesting. `~/Library/Containers/` is usually used by sandboxed apps, which is not the case for Sketch since a long time. Maybe there are some broken links that go back to when you had the app downloaded from the mac app store?
