### ISSUE TITLE
Disabled Data functionality

### ISSUE THREAD

**Issue by konki-vienna** [BohemianCoding/SketchAPI#457]
When adding `require('sketch/dom').getSelectedDocument()` to the code of a Data Plugin, the Data Plugin part of that plugin gets disabled (through Sketch) without the possibility to enable it again (through the user).

Environment: Sketch Version 54, Mac OS Mojave (v. 10.14.3)
How to reproduce:

1. Create a Sketch Data Plugin 
2. Add the code `let document = require('sketch/dom').getSelectedDocument()` to the data related JS file.
3. Build the plugin
4. Open Sketch
5. Go to `Sketch` > `Preferences` > `Data` and scroll to the specific Data Plugin line - the plugin is disbaled (see screenshot attached).
![Bildschirmfoto 2019-04-10 um 10 42 51](https://user-images.githubusercontent.com/5039952/55864905-a80d6300-5b7d-11e9-979e-0c8d339b1fa6.png)

**Comment by mathieudutour** [comment]
Where exactly are you adding it?

**Comment by konki-vienna** [comment]
I was adding it outside `onStartup()`:
```
const sketch = require('sketch')
const { DataSupplier } = sketch
const util = require('util')

let document = require('sketch/dom').getSelectedDocument()

export function onStartup () {
  // To register the plugin, uncomment the relevant type:
  DataSupplier.registerDataSupplier('public.text', 'data_test', 'SupplyData')
  // DataSupplier.registerDataSupplier('public.image', 'data_test', 'SupplyData')
}

export function onShutdown () {
  // Deregister the plugin
  DataSupplier.deregisterDataSuppliers()
}

export function onSupplyData (context) {
  let dataKey = context.data.key
  const items = util.toArray(context.data.items).map(sketch.fromNative)
  items.forEach((item, index) => {
    let data = Math.random().toString()
    DataSupplier.supplyDataAtIndex(dataKey, data, index)
  })
}
```
but when I add it to/inside `onStartup()` everything seems to be fine. 🤦‍♂️
Probably this is the right place to put it, right?

```
const sketch = require('sketch')
const { DataSupplier } = sketch
const util = require('util')

export function onStartup () {
  let document = require('sketch/dom').getSelectedDocument()
  // To register the plugin, uncomment the relevant type:
  DataSupplier.registerDataSupplier('public.text', 'data_test', 'SupplyData')
  // DataSupplier.registerDataSupplier('public.image', 'data_test', 'SupplyData')
}

export function onShutdown () {
  // Deregister the plugin
  DataSupplier.deregisterDataSuppliers()
}

export function onSupplyData (context) {
  let dataKey = context.data.key
  const items = util.toArray(context.data.items).map(sketch.fromNative)
  items.forEach((item, index) => {
    let data = Math.random().toString()
    DataSupplier.supplyDataAtIndex(dataKey, data, index)
  })
}
```

**Comment by mathieudutour** [comment]
Yeah it might do something funky outside `onStartup` because when it will be run. 
Even `onStartup` might not have a document.

**Comment by konki-vienna** [comment]
So better put it inside `onSupplyData`?

**Comment by mathieudutour** [comment]
Yeah, better put it in the function where you need it :)

**Comment by konki-vienna** [comment]
Yes, thank you!
PS.: I guess you (and not me) close the issue then - I do not know what the protocol here is...

**Comment by konki-vienna** [comment]
Ah, one last question: Would there have been any way to get some debug-info here (regarding the disabled Data-plugin part). I was looking into the MacOs Console (filtered for Sketch), but there is so much going on when Sketch starts that I did not see anything which looked connected...

**Comment by mathieudutour** [comment]
It's actually a bug that `getSelectedDocument` throws an error when there is no document so I'll fix that!
