### ISSUE TITLE
plugin update with appcast.xml

### ISSUE THREAD

**Issue by DrinkingWords** [BohemianCoding/SketchAPI#458]
I am trying to send an update to everyone who downloaded my plugin from a server. I provide an appcast.xml file and link it to my manifest.json. The appcast.xml file contains all zip file for different version plugins, as well as urls to download each one. Then sketch shows 'Plugin Update Available' on the top right corner. But when I click the update button, the plugin is uninstalled. 
I got the error 'Missing plugin manifest.json at URL: file:///.../SketchCloud1.0.2.sketchplugin/Contents/Sketch/manifest.json");'
But when  I open the url in appcast.xml in browser, I can download the plugin successfully. am I missing something?

I can update plugin successfully by clicking the update button when the server is a local server. (hs -p -o 9999)

**Comment by mathieudutour** [comment]
Do you have the link to your appcast?

**Comment by DrinkingWords** [comment]
I add this line to the manifest file.
"appcast": "http://10.25.136.119:9999/view/plugin/appcast.xml".

Is there any requirements for the server?

**Comment by mathieudutour** [comment]
It needs to be https
