### ISSUE TITLE
Feature Request: webview window

### ISSUE THREAD

**Issue by amin-nas** [BohemianCoding/SketchAPI#46]
Any plans to add a method for creating webview modal, something like:
Application.openWebview(URL, size, callback)

If anyone has created something like that, would love to hear about it.

**Comment by mathieudutour** [comment]
I did something like that: https://github.com/mathieudutour/sketch-module-web-view

You will need to compile your code to use it though (you can use this: https://github.com/sketch-pm/skpm#im-a-plugin-developer)

**Comment by amin-nas** [comment]
Got it working with skpm 💥
Enabling the community to build on each other work is a game changer. As a designer new to coding, I spent days trying to do the same thing by myself. Hoping other people can find, use, and contribute to skpm.
