### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by DrinkingWords** [BohemianCoding/SketchAPI#462]
I still lost about #458. I may find the reason. when I add ""assets": [ "assets/**/*" ]" to the package.json and the plugin is updated successfully. But when I add " "assets": [ "assets/**/*", "../panel/dist"]",  the plugin is  not updated successfully.  Because there is no sketch folder in /SketchCloud1.0.2.sketchplugin/Contents, only Resources folder.

The panel/dist  is build by vue.js.  
I try to move dist to assets folder so that I dont need to add ""assets": ../pamel/dist" to the package.json, but the sketch crashes. I think it is because that I use sketch-module-web-view and the communication between the Plugin and the WebView losts. 

The following is the assets folder:
assets
     ...
     dist
         index.html
         static
             css
             js
             image
So how can I update the plugin with appcast?

**Comment by mathieudutour** [comment]
Can you open an issue on `skpm/skpm`? That has nothing to do with the Sketch API.

Also if you can provide a link to your plugin repo, that'd be helpful
