### ISSUE TITLE
Getting CurvePoint’s variables

### ISSUE THREAD

**Issue by KevinGutowski** [BohemianCoding/SketchAPI#470]
Similar to how I can set a `ShapePath` as a variable like so:

```
let sketch = require('sketch')
let ShapePath = sketch.ShapePath
let oval = ShapePath.ShapeType.Oval
```

How come I can’t do the same with `CurvePoint`

```
let sketch = require('sketch')
let CurvePoint = sketch.CurvePoint
let straight = CurvePoint.PointType.Straight
```

I’m trying to get at the variable `PointType`  and use it like so:

```
let sketch = require('sketch’)
let ShapePath = sketch.ShapePath
let CurvePoint = sketch.CurvePoint

let straight = CurvePoint.PointType.Straight

let myLine = new sketch.ShapePath({
  name: 'myLine',
  frame: {x: 10, y: 0, width: 40, height: 100},
  style: { borders: ['#FF0000'] },
  points: [{ point: { x: 0, y: 0 }, pointType: straight}, { point: { x: 1, y: 1 }, pointType: straight}],
  parent: myArtboard,
  closed: false
})
```

**Comment by mathieudutour** [comment]
Ah because `CurvePoint` isn't exposed so `sketch.CurvePoint` is undefined.

I don't really want to expose CurvePoint as there is no use to it so I might expose `PointType` on `ShapePath` instead

**Comment by KevinGutowski** [comment]
Ah makes sense. Could you clarify what you mean by “exposed”? I was looking for somewhere in the code that exposes `ShapePath` (and thus implicitly not exposing `CurvePoint`)

**Comment by mathieudutour** [comment]
By exposed I mean exported 😛 
When you do `require('sketch')`, the object that you get is this one: https://github.com/BohemianCoding/SketchAPI/blob/develop/Source/dom/index.js#L45-L77
You can see that `ShapePath` is there but `CurvePoint` isn't

**Comment by KevinGutowski** [comment]
Ahh that’s right! That’s file that I have been messing with to try and get the API working locally. All makes sense now. Thanks for the extra clarification!

**Comment by jedrichards** [comment]
@mathieudutour So I'm guessing this is as simple as grabbing a reference to `PointType` and exposing it on `ShapePath`, somewhere around [here]()https://github.com/BohemianCoding/SketchAPI/blob/develop/Source/dom/layers/ShapePath.js#L120 like this? -

```
ShapePath.PointType = PointType
```

**Comment by mathieudutour** [comment]
That's the API I was thinking of yes. Maybe with a couple of tests to make sure it's correctly exported
