### ISSUE TITLE
centerOnLayer not centering nested layers

### ISSUE THREAD

**Issue by jeroenknol** [BohemianCoding/SketchAPI#471]
Currently i am working on a plugin that scans your Sketch for all colors you have used in the document and list them for you per color. In the tree structure we list all the layers, and clicking them selects them and does a `centerOnLayer` in sketch.

This works fine for layers that are not nested:
<img width="1680" alt="Screenshot 2019-04-18 at 10 01 40" src="https://user-images.githubusercontent.com/22663593/56345903-1f1baa80-61c1-11e9-9935-b1887f8a7755.png">
<img width="1680" alt="Screenshot 2019-04-18 at 10 02 14" src="https://user-images.githubusercontent.com/22663593/56345904-1f1baa80-61c1-11e9-9ff6-9fe13a7df1cd.png">

But for the layers that are in the group, the nested layers, the `centerOnLayer` does not center the layers but puts the off to the bottom right as you can see here:
<img width="1680" alt="Screenshot 2019-04-18 at 10 02 33" src="https://user-images.githubusercontent.com/22663593/56346007-63a74600-61c1-11e9-9c46-8d33256e53c7.png">

Here is the function that is being called from the webview:
``` javascript
  webContents.on('selectLayer', (layerID) => {
    const document = sketch.getDocuments()[0];
    const sketchLayer = document.getLayerWithID(layerID);
    document.centerOnLayer(sketchLayer);
    document.selectedLayers = [sketchLayer];
  });
```

It feels to me like it's an issue with the nesting/centerOnLayer, but maybe i am doing something wrong. Any help would be much appreciated!

**Comment by chriswetterman** [comment]
Thanks for opening an issue @jeroenknol. I have seen some inconsistencies and am trying to track down a similar, if not the same issue. For me, one was needing to set `document.selectedPage` if the layer I was centering was not on the current page. Still though I have cases where centering moves the layer and its containing artboard 100% completely out of view on the page.

**Comment by chriswetterman** [comment]
I am not sure if this is the same issue causing the symptoms described by @jeroenknol, but I will post screenshots of what is happening for me. The 1st screenshot shows the original canvas position. The 2nd screenshot is after I call centerOnLayer for the 'hello' text field. 

<img width="1116" alt="Screen Shot 2019-05-04 at 8 44 57 PM" src="https://user-images.githubusercontent.com/171418/57186443-933a9b80-6ead-11e9-9de2-6bc3d6d5afb5.png">

<img width="1114" alt="Screen Shot 2019-05-04 at 8 45 12 PM" src="https://user-images.githubusercontent.com/171418/57186444-9a61a980-6ead-11e9-94da-c3a6e96f95e2.png">
