### ISSUE TITLE
Sketch Cloud - upload timeout issues

### ISSUE THREAD

**Issue by laurenmrice** [BohemianCoding/SketchAPI#473]
I am trying to push out a new update to the Carbon Design System sketch file using Sketch Cloud so the designers that use our system can get their updates to their files, but I keep getting this timeout error.
![Screen Shot 2019-04-17 at 1 34 47 PM](https://user-images.githubusercontent.com/43969356/56430879-77b87980-628d-11e9-8fee-b9e8c3d25762.png)
The file is only 11 MB so I don't think it's a complexity issue? I have tried to do this on different internet connections, on different computers etc, and still am not having luck.

Any help would be greatly appreciated! Thanks

**Comment by KevinGutowski** [comment]
Heya @laurenmrice I’m not really sure what is going wrong with your issue. Since this GitHub project is all about the Sketch Javascript API, I think you would have better luck contacting [Sketch support](https://www.sketch.com/support/contact/?topic=bug).

**Comment by laurenmrice** [comment]
@KevinGutowski Yeah I tried that last week but haven't heard back yet. Will keep trying ! Thanks.

**Comment by KevinGutowski** [comment]
Ah darn, the only thing I can think of right now would be to log out of Sketch Cloud both in the browser and in Sketch and then log back in. ¯\_(ツ)_/¯

**Comment by mathieudutour** [comment]
I believe the Sketch support answered the email so I'm going to close this, not much we can do as port of the JS API anyway
