### ISSUE TITLE
Changelog didn't get updated with 55

### ISSUE THREAD

**Issue by KevinGutowski** [BohemianCoding/SketchAPI#478]
Congrats with the beta release! 🎉

It would be helpful to know if there were any updates to the API. I couldn't find much here:
https://github.com/BohemianCoding/SketchAPI/compare/release/55

And the changelog didn't get updated:
https://github.com/BohemianCoding/SketchAPI/blob/release/55/CHANGELOG.json

**Comment by mathieudutour** [comment]
It's everything that is in "unreleased".

**Comment by KevinGutowski** [comment]
Ok! That's what I figured. Thanks! 👍

**Comment by mathieudutour** [comment]
Also, not really part of the API but related to plugin dev:
- The way errors were logged right now was pretty bad:
```
const err = new Error("This is an error")
console.log(err)
---
{ onRun@/***/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:8:22
  line: 8,
  column: 22,
  sourceURL: '/***/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin' }
```

```
throw new Error('this is an error')
---
Error: This is an error
line: 2
sourceURL: /Users/mathieudutour/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin
column: 26
stack: onRun@/Users/mathieudutour/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:2:26
```

It was not consistent and not pretty.

Now it's consistent (and match how errors are logged in Node):
```
Error: This is an error
    at onRun (/Users/mathieudutour/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:2:26)
```

- There is a new action "HandleURL": https://github.com/BohemianCoding/SketchAPI/blob/release/55/docs/actions/HandleURL.md which is super useful for oauth, etc.
- there will be the new documentation #421 hopefully
