### ISSUE TITLE
Copy crashes sketch

### ISSUE THREAD

**Issue by KevinGutowski** [BohemianCoding/SketchAPI#482]
I was trying to copy some JSON representation to the buffer with `copy` and it crashes Sketch.

```
let x = { property: 1, prop1: 2, method: function(){}}
copy(x)
```

**Comment by mathieudutour** [comment]
I don't think `copy` does what you think it does. It's not in the JS spec. In Sketch it's an obj-c method that copy an object and retains it. Bad stuff to do in cocoascript, I'm not surprised it's crashing 😬

**Comment by mathieudutour** [comment]
I'll fix the crash and make `copy` return undefined tho

**Comment by mathieudutour** [comment]
It's gonna be fixed by a PR on Sketch. Closing this
