### ISSUE TITLE
console.dir doesn’t seem to be working

### ISSUE THREAD

**Issue by KevinGutowski** [BohemianCoding/SketchAPI#483]
Been reading this book on JS (http://www.javascriptgrammar.com/) and found this interesting method on `console`

<img width="695" alt="image" src="https://user-images.githubusercontent.com/4199296/56948034-b8ad5b00-6ae3-11e9-91e5-c088984d5930.png">

```
let x = { property: 1, prop1: 2, method: function(){}}
console.dir(x)
```

Logs:
```
TypeError: second argument to Function.prototype.apply must be an Array-like object (evaluating 'util.format.apply(this, payload)')
    at logEverywhere (/Applications/Sketch Beta.app/Contents/Resources/core-modules/@skpm/console/index.js:20:38)
    at dir (/Applications/Sketch Beta.app/Contents/Resources/core-modules/@skpm/console/index.js:94:25)
    at onRun (/Users/Kski/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:4:12)
```
I realize in the past you have also pointed me to `Object.keys` & `Object.getOwnPropertyNames(artboard.__proto__)` for this type of thing.

**Comment by mathieudutour** [comment]
The only difference between console.log and console.dir is that console.dir accept an options object as the second argument that is passed to the `util.inspect` function. I've never used it tbh (that's why I forgot to test it 😬 )
