### ISSUE TITLE
getLibraryForDocumentAtPath and getRemoteLibraryWithRSS insufficient

### ISSUE THREAD

**Issue by uxcourt** [BohemianCoding/SketchAPI#496]
My goal is to generate a list of specific IDs for two layer styles, and two text style, and toggle between them (think showLayer > hideLayer and applyTextStyle1 > applyTextStyle2).

All the styles are stored in an external library, and both the working files and the library are managed by Abstract.

getLibraryForDocumentAtPath won't work because Abstract manages the file path and it's a calculation of the current branch of a shared repo; not only does Abstract place the file in a branch-specific, dynamically calculated path, the file name gets appended with some kind of checksum. The file path isn't an option without opening up an Abstract API too.

getRemoteLibraryWithRSS won't work because the URLs for the Abstract-hosted library are variable based on the branch and the checkout status, and Abstract doesn't host an RSS feed with a more direct path to the library file.

Why can we not use some attribute retrieved by the getLibraries function to load up a specific library? Sketch already knows the relationship between the work file and its library. How can I load all the sharedLayerStyles and sharedTextStyles from the library without using the file path or an RSS feed to point to the library?

**Comment by mathieudutour** [comment]
You can totally use any of the properties of the libraries to retrieve one from `getLibraries`:
```js
const libraries = Libraries.getLibraries()

const myLibrary = libraries.find(l => l.name === 'my-name')
```

`getLibraryForDocumentAtPath` and `getRemoteLibraryWithRSS` are used to the library for a local Sketch document (or rss feed). If the Document was already added as a Library, it will simply return it. If it is not already a Library, it will be added.

**Comment by uxcourt** [comment]
maybe just include in the documentation that there is a way to access/import library styles besides passing a file path or an RSS feed. I found sample code for this in another section of the documentation.

```
function trackSymbols(symbol){
	var sMaster=symbol.master;
    var originLibrary=sMaster.getLibrary();
    var layerStylesReferences=originLibrary.getImportableLayerStyleReferencesForDocument(document);
    var textStylesReferences=originLibrary.getImportableTextStyleReferencesForDocument(document);
}
```

I found this method of accessing the source library on the https://developer.sketch.com/reference/api/#get-the-shared-layer-styles-that-can-be-imported page, and perhaps it would be helpful if this was cross-referenced from https://developer.sketch.com/reference/api/#access-all-the-libraries

**Comment by mathieudutour** [comment]
you mean the `sMaster.getLibrary()` method? It's documented under the Symbol Master section because it's a symbol master method.

The same method exists for Shared Styles btw. 
Documenting this method under Library would make it really confusing IMO since you would need to document Symbols and Shared Styles before.

But maybe I'm misunderstanding. Feel free to open a PR with how you think it should be!

**Comment by uxcourt** [comment]
You're probably right; too much cross referencing would make the docs a mess. It might be worth consider a sidebar style treatment on related topics, but you're right: either way there's a lot of baseline understanding required.
