### ISSUE TITLE
Add the thinkness of border with new API

### ISSUE THREAD

**Issue by wodory** [BohemianCoding/SketchAPI#50]
I'm modifing my plugin, flowmate, to fix errors and update new APIs. It's really hard to understand the new and old APIs because there is not useful example. Your example is just for few cases and most of plugin still use old API (Please add some example to API documents)

And I have one questions. Do you have a plan to change thinkness of shape using new API? I saw the "Style.js" source and the implement is not hard I guess. That's why I don't understand you don't implement thickness (and gradient)

P.S : Is this way to I modify the core script like Style.js and test directly on Sketch app?

**Comment by matt-curtis** [comment]
You can modify `Sketch.app/Resources/SketchAPI.js`. That's where the JS API lives in releases of Sketch. :)

**Comment by wodory** [comment]
Sounds Good! Thanks!
