### ISSUE TITLE
shortcut only works when Plugins menu is already open

### ISSUE THREAD

**Issue by uxcourt** [BohemianCoding/SketchAPI#521]
I've updated the manifest.json file for my plug in as shown here:

```
{
  "compatibleVersion": 3,
  "bundleVersion": 1,
  "author": "Premera Design",
  "icon": "icon.png",
  "commands": [
    {
      "name": "Toggle Symbol Overlays",
      "identifier": "symbol-overlay-toggle.toggle",
      "shortcut": "option shift L",
      "script": "my-command.js"
    }
  ],
  "menu": {
    "title": "Toggle Symbol Overlays",
    "items": [
      "symbol-overlay-toggle.toggle"
    ],
    "isRoot":true
  },
  "version": "0.1.0",
  "description": "",
  "name": "symbol-overlay-toggle",
  "identifier": "symbol-overlay-toggle",
  "disableCocoaScriptPreprocessor": true,
  "appcast": "https://github.com/uxcourt/overlaytoggler/blob/master/.appcast.xml"
}
```

When I build using 

> npm run-script build 

My plugin gets the correct icons next to it in the Plugins menu, but those keystrokes are not functional until the Plugins menu is already opened.

This is clearly not the case with other plugin shortcuts. What am I missing?

I've also tried 
`"shortcut": "cmd option o",`

and 
`"shortcut": "cmd shift O",`

but in both those cases, the icons next to the menu don't even show up.

**Comment by uxcourt** [comment]
> ctrl cmd o 

works as expected. It would be nice to know why the others failed.

**Comment by mathieudutour** [comment]
a shortcut won't work if it's already used by Sketch (or another plugin depending on the order in which Sketch loads them)
