### ISSUE TITLE
library's url

### ISSUE THREAD

**Issue by DrinkingWords** [BohemianCoding/SketchAPI#522]
I get a remote library from an url, like this:
Library.getRemoteLibraryWithRSS(
  url,
  (err, library) => {
  }
)
How can I get the url from the library?
I try this: library.getDocument().path. 
I got "https://developer.apple.com/design/downloads/sketch.rss". But I want to get the url where the rss.xml exits.

**Comment by DrinkingWords** [comment]
If the rss.xml has a chinese name, or the sketch has a chinese name, can I add the remote sketch to library?

**Comment by mathieudutour** [comment]
> But I want to get the url where the rss.xml exits.

I'm not sure what that means. Do you mean getting `https://developer.apple.com/design/downloads`?

> can I add the remote sketch to library?

I don't see why not

**Comment by DrinkingWords** [comment]
1. For example:
Library.getRemoteLibraryWithRSS(
'http://10.21.225.79:8080/sketch/rss.xml',
(err, library) => {
}
I want to get this url: 'http://10.21.225.79:8080/sketch/rss.xml'.
2. When the sketch has a Chinese name, I can not add it to library. Neither 'err.message' nor 'library.name' was excuted.
Library.getRemoteLibraryWithRSS(
encodeURI('http://10.21.225.79:8080/sketch/测试.xml'),
(err, library) => {
   if (err) {
      console.log(err.message)
   } esle {
     console.log(library.name)
  }
})
