### ISSUE TITLE
Not able to delete the key from layer settings using Settings.setLayerSettingForKey

### ISSUE THREAD

**Issue by pratyushtewari** [BohemianCoding/SketchAPI#529]
The key should be deleted from the layer user info by passing `undefined` in the `Settings.setLayerSettingForKey(layer, 'my-key', undefined)` but the key is not removed and the value is set to null.

May be implement `removeObjectForKey(key)` when the value is undefined at

https://github.com/BohemianCoding/SketchAPI/blob/cea79d8b9b37f2c21064f7ddd310eaa5862bda7d/Source/settings/Settings.js#L116 

Ref: https://sketchplugins.com/d/1433-how-to-delete-a-layer-setting

**Comment by mathieudutour** [comment]
So I can't reproduce. What version of Sketch are you using?

here is how I test it:
```js
setLayerSettingForKey(layer, 'object-key', { a: 1 })
setLayerSettingForKey(layer, 'object-key-2', { a: 2 })
console.log(layerSettingForKey(layer, 'object-key')) // {a: 1}

setLayerSettingForKey(layer, 'object-key', undefined)
console.log(layerSettingForKey(layer, 'object-key')) // undefined
console.log(layer.sketchObject.userInfo()['io.skpm.tests-runner']) // { 'object-key-2': '{"a":1}' }
```

**Comment by pratyushtewari** [comment]
I am unfortunately stuck on v52.5 (company is too slow to upgrade).
When I run 
`setLayerSettingForKey(layer, 'object-key', undefined)`
I get the error
`values passed to setValue:forKey:onObject:forPluginIdentifier:: must be composed of arrays, dictionaries, numbers and strings`
and maybe that is the reason I cannot set the value to undefined and it is not deleted. I'll close this issue and check back once the version is upgraded to 55.

Thanks!
