### ISSUE TITLE
export foreign symbols

### ISSUE THREAD

**Issue by DrinkingWords** [BohemianCoding/SketchAPI#530]
Is there any way to export a group layer in foreign symbols to buffer?
I try this and get an error.
```js
let symbolReferences = library.getImportableSymbolReferencesForDocument(document);
symbolReferences.forEach(importableSymbol => {
        let symbolReference = importableSymbol.import();
        let layers = symbolReference.layers;
        let options = { formats: 'svg', output: false };
        for (let i = 0; i < layers.length; i++) {
             if (layers[i].type === 'Group') {
                    var duplicatedLayer = layers[i].duplicate();
                    let buffer = sketch.export(duplicatedLayer, options);
                    break;
             }
         }
})
```
When the group is in current document, not in library, I can export it to svg successfully.

**Comment by mathieudutour** [comment]
what's the error?

**Comment by DrinkingWords** [comment]
I am sorry I don not understand the error.
Perhaps at this line:
l = MSExporter.exporterForRequest_colorSpace_driver(u, s, i.driver()).data();
I got the error: 
err.message: "An Obj-c exception occurred"
err.sourceURL: "Applications/sketch.app/Contents/Resources/SketchAPI_dom.js"

**Comment by DrinkingWords** [comment]
Another issue:
I export two different svgs.  when I put them in two htmls, they look different. But when I put them in one html, they look same!
first one:
<!DOCTYPE html>
<html>
<body>
<svg width="96px" height="96px" viewBox="0 0 96 96" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>ic/vip/ic_vip_filled</title>
    <desc>Created with Sketch.</desc>
    <defs>
        <path d="M20,68 L68,68 C70.209139,68 72,69.790861 72,72 L72,72 C72,74.209139 70.209139,76 68,76 L20,76 C17.790861,76 16,74.209139 16,72 L16,72 C16,69.790861 17.790861,68 20,68 Z M42.0288552,11.6687042 C39.6834099,10.8532339 38,8.62320765 38,6 C38,2.6862915 40.6862915,0 44,0 C47.3137085,0 50,2.6862915 50,6 C50,8.62320765 48.3165901,10.8532339 45.9711448,11.6687042 L60,36 L77.0551919,25.3993477 C76.3896428,24.4330622 76,23.2620341 76,22 C76,18.6862915 78.6862915,16 82,16 C85.3137085,16 88,18.6862915 88,22 C88,25.3137085 85.3137085,28 82,28 C81.6575459,28 81.3217926,27.9713101 80.9950127,27.9162027 L73.322897,58.6931541 C72.5455362,61.8115629 69.7445917,64 66.5307523,64 L21.5219885,64 C18.2837974,64 15.4682796,61.7789633 14.7143545,58.6297605 L7.34528569,27.8485973 C6.91281267,27.9476663 6.46251793,28 6,28 C2.6862915,28 0,25.3137085 0,22 C0,18.6862915 2.6862915,16 6,16 C9.3137085,16 12,18.6862915 12,22 C12,23.2016647 11.6467427,24.3208218 11.0384112,25.2592881 L28,36 L42.0288552,11.6687042 Z" id="path-1"></path>
    </defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="ic/vip/ic_vip_filled">
            <g id="symbol/frame/symbol_grid24"></g>
            <g id="Group" transform="translate(4.000000, 8.000000)">
                <mask id="mask-2" fill="white">
                    <use xlink:href="#path-1"></use>
                </mask>
                <use id="Combined-Shape-Copy" fill="#000000" xlink:href="#path-1"></use>
                <rect id="color/#000000" fill="#000000" mask="url(#mask-2)" x="-4" y="-8" width="96" height="96"></rect>
            </g>
        </g>
    </g>
</svg>
</body>
</html>

second one:
<!DOCTYPE html>
<html>
<body>
<svg width="96px" height="96px" viewBox="0 0 96 96" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>ic/category/ic_category_filled</title>
    <desc>Created with Sketch.</desc>
    <defs>
        <path d="M12,0 L68,0 C74.627417,-1.21743675e-15 80,5.372583 80,12 L80,68 C80,74.627417 74.627417,80 68,80 L12,80 C5.372583,80 8.11624501e-16,74.627417 0,68 L0,12 C-8.11624501e-16,5.372583 5.372583,1.21743675e-15 12,0 Z M20,36 C25.5228475,36 30,31.5228475 30,26 C30,20.4771525 25.5228475,16 20,16 C14.4771525,16 10,20.4771525 10,26 C10,31.5228475 14.4771525,36 20,36 Z M20,64 C25.5228475,64 30,59.5228475 30,54 C30,48.4771525 25.5228475,44 20,44 C14.4771525,44 10,48.4771525 10,54 C10,59.5228475 14.4771525,64 20,64 Z M38,23 L67.2391031,23 C68.3436726,23 69.2391031,22.1045695 69.2391031,21 C69.2391031,19.8954305 68.3436726,19 67.2391031,19 L38,19 C36.8954305,19 36,19.8954305 36,21 C36,22.1045695 36.8954305,23 38,23 Z M38,33 L67.2391031,33 C68.3436726,33 69.2391031,32.1045695 69.2391031,31 C69.2391031,29.8954305 68.3436726,29 67.2391031,29 L38,29 C36.8954305,29 36,29.8954305 36,31 C36,32.1045695 36.8954305,33 38,33 Z M38,51 L67.2391031,51 C68.3436726,51 69.2391031,50.1045695 69.2391031,49 C69.2391031,47.8954305 68.3436726,47 67.2391031,47 L38,47 C36.8954305,47 36,47.8954305 36,49 C36,50.1045695 36.8954305,51 38,51 Z M38,61 L67.2391031,61 C68.3436726,61 69.2391031,60.1045695 69.2391031,59 C69.2391031,57.8954305 68.3436726,57 67.2391031,57 L38,57 C36.8954305,57 36,57.8954305 36,59 C36,60.1045695 36.8954305,61 38,61 Z" id="path-1"></path>
    </defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="ic/category/ic_category_filled">
            <g id="symbol/frame/symbol_grid24"></g>
            <g id="Group-9" transform="translate(8.000000, 8.000000)">
                <mask id="mask-2" fill="white">
                    <use xlink:href="#path-1"></use>
                </mask>
                <use id="Combined-Shape" fill="#000000" xlink:href="#path-1"></use>
                <g id="color/light/#000000" mask="url(#mask-2)" fill="#000000">
                    <g transform="translate(-8.000000, -8.000000)" id="color/#000000">
                        <rect x="0" y="0" width="96" height="96"></rect>
                    </g>
                </g>
                <g id="Group-7" mask="url(#mask-2)">
                    <g transform="translate(36.000000, 19.000000)"></g>
                </g>
                <g id="Group-8" mask="url(#mask-2)">
                    <g transform="translate(36.000000, 47.000000)"></g>
                </g>
            </g>
        </g>
    </g>
</svg>
</body>
</html>

put them together:
<!DOCTYPE html>
<html>
<body>
<svg width="96px" height="96px" viewBox="0 0 96 96" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>ic/category/ic_category_filled</title>
    <desc>Created with Sketch.</desc>
    <defs>
        <path d="M12,0 L68,0 C74.627417,-1.21743675e-15 80,5.372583 80,12 L80,68 C80,74.627417 74.627417,80 68,80 L12,80 C5.372583,80 8.11624501e-16,74.627417 0,68 L0,12 C-8.11624501e-16,5.372583 5.372583,1.21743675e-15 12,0 Z M20,36 C25.5228475,36 30,31.5228475 30,26 C30,20.4771525 25.5228475,16 20,16 C14.4771525,16 10,20.4771525 10,26 C10,31.5228475 14.4771525,36 20,36 Z M20,64 C25.5228475,64 30,59.5228475 30,54 C30,48.4771525 25.5228475,44 20,44 C14.4771525,44 10,48.4771525 10,54 C10,59.5228475 14.4771525,64 20,64 Z M38,23 L67.2391031,23 C68.3436726,23 69.2391031,22.1045695 69.2391031,21 C69.2391031,19.8954305 68.3436726,19 67.2391031,19 L38,19 C36.8954305,19 36,19.8954305 36,21 C36,22.1045695 36.8954305,23 38,23 Z M38,33 L67.2391031,33 C68.3436726,33 69.2391031,32.1045695 69.2391031,31 C69.2391031,29.8954305 68.3436726,29 67.2391031,29 L38,29 C36.8954305,29 36,29.8954305 36,31 C36,32.1045695 36.8954305,33 38,33 Z M38,51 L67.2391031,51 C68.3436726,51 69.2391031,50.1045695 69.2391031,49 C69.2391031,47.8954305 68.3436726,47 67.2391031,47 L38,47 C36.8954305,47 36,47.8954305 36,49 C36,50.1045695 36.8954305,51 38,51 Z M38,61 L67.2391031,61 C68.3436726,61 69.2391031,60.1045695 69.2391031,59 C69.2391031,57.8954305 68.3436726,57 67.2391031,57 L38,57 C36.8954305,57 36,57.8954305 36,59 C36,60.1045695 36.8954305,61 38,61 Z" id="path-1"></path>
    </defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="ic/category/ic_category_filled">
            <g id="symbol/frame/symbol_grid24"></g>
            <g id="Group-9" transform="translate(8.000000, 8.000000)">
                <mask id="mask-2" fill="white">
                    <use xlink:href="#path-1"></use>
                </mask>
                <use id="Combined-Shape" fill="#000000" xlink:href="#path-1"></use>
                <g id="color/light/#000000" mask="url(#mask-2)" fill="#000000">
                    <g transform="translate(-8.000000, -8.000000)" id="color/#000000">
                        <rect x="0" y="0" width="96" height="96"></rect>
                    </g>
                </g>
                <g id="Group-7" mask="url(#mask-2)">
                    <g transform="translate(36.000000, 19.000000)"></g>
                </g>
                <g id="Group-8" mask="url(#mask-2)">
                    <g transform="translate(36.000000, 47.000000)"></g>
                </g>
            </g>
        </g>
    </g>
</svg>
<svg width="96px" height="96px" viewBox="0 0 96 96" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>ic/vip/ic_vip_filled</title>
    <desc>Created with Sketch.</desc>
    <defs>
        <path d="M20,68 L68,68 C70.209139,68 72,69.790861 72,72 L72,72 C72,74.209139 70.209139,76 68,76 L20,76 C17.790861,76 16,74.209139 16,72 L16,72 C16,69.790861 17.790861,68 20,68 Z M42.0288552,11.6687042 C39.6834099,10.8532339 38,8.62320765 38,6 C38,2.6862915 40.6862915,0 44,0 C47.3137085,0 50,2.6862915 50,6 C50,8.62320765 48.3165901,10.8532339 45.9711448,11.6687042 L60,36 L77.0551919,25.3993477 C76.3896428,24.4330622 76,23.2620341 76,22 C76,18.6862915 78.6862915,16 82,16 C85.3137085,16 88,18.6862915 88,22 C88,25.3137085 85.3137085,28 82,28 C81.6575459,28 81.3217926,27.9713101 80.9950127,27.9162027 L73.322897,58.6931541 C72.5455362,61.8115629 69.7445917,64 66.5307523,64 L21.5219885,64 C18.2837974,64 15.4682796,61.7789633 14.7143545,58.6297605 L7.34528569,27.8485973 C6.91281267,27.9476663 6.46251793,28 6,28 C2.6862915,28 0,25.3137085 0,22 C0,18.6862915 2.6862915,16 6,16 C9.3137085,16 12,18.6862915 12,22 C12,23.2016647 11.6467427,24.3208218 11.0384112,25.2592881 L28,36 L42.0288552,11.6687042 Z" id="path-1"></path>
    </defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="ic/vip/ic_vip_filled">
            <g id="symbol/frame/symbol_grid24"></g>
            <g id="Group" transform="translate(4.000000, 8.000000)">
                <mask id="mask-2" fill="white">
                    <use xlink:href="#path-1"></use>
                </mask>
                <use id="Combined-Shape-Copy" fill="#000000" xlink:href="#path-1"></use>
                <rect id="color/#000000" fill="#000000" mask="url(#mask-2)" x="-4" y="-8" width="96" height="96"></rect>
            </g>
        </g>
    </g>
</svg>
</body>
</html>

**Comment by DrinkingWords** [comment]
There are <defs> element in svg. They've all got the same id, so this causes problems when they appear on the same page.
<svg>
<defs>
  <circle id="path-1" … ></circle>
</defs>
<g id="some-icon">
  <circle ...></circle>
  <use xlink:href="#path-1"></use>
</g>
</svg>
Is there anything I can do?

**Comment by DrinkingWords** [comment]
let options = { formats: 'png', output: false };
let buffer = sketch.export(duplicatedLayer, options);
After I  get the buffer ,I send it to the webview. How can it change to png in html?

**Comment by DrinkingWords** [comment]
I want to change layers to image and show them in webview.  When I change the layers to sygs, they've all got the same id so that I can not show them in a html. When I change the layers to pngs, I got the buffer but I dont know how to change them to png back in webview.

**Comment by mathieudutour** [comment]
So a few things here:
1. You can't export symbols or layers that aren't in a document. So you need to either insert the imported symbol in the document or just don't import it and use the library's document directly. There is a PR opened to improve the error message here: https://github.com/BohemianCoding/SketchAPI/pull/409
2. for the duplicated ids, you can parse the svg and remove them, or render the SVGs in different iframes
3. you need to serialise the buffer to be able to send it to the webview: `buffer.toString('base64')` and then render the png from its base64 representation
