### ISSUE TITLE
Add support for Document's color profile

### ISSUE THREAD

**Issue by mathieudutour** [BohemianCoding/SketchAPI#531]
A Document can have a different color profiles (sRGB, P3, auto). We need to expose it in the API.

**Comment by jedrichards** [comment]
@mathieudutour By "expose" do you mean simply get a string representing the current selection? As opposed to also changing it?

**Comment by mathieudutour** [comment]
Both

**Comment by jedrichards** [comment]
@mathieudutour Made a start on this in #533. I think the getter is working. The setter isn't working (current approach just a stab in the dark), any pointers how to proceed? I've no idea even the general approach ... is this something that needs new functionality in Sketch? Or if not, how to go about finding the correct native objects/method calls?

**Comment by jedrichards** [comment]
Hmm, just looked at the [tests](https://github.com/BohemianCoding/Sketch/blob/develop/Modules/SketchControllers/Tests/Classes/ColorSpaceTests.swift) in the Sketch repo.

How does this look for the setter?

```
const documentData = this._getMSDocumentData()
documentData.assignColorSpace(colorSpace)
```

**Comment by mathieudutour** [comment]
Yep, looks like it. You might want to ask the mac devs what's the difference between `assignColorSpace` and `convertToColorSpace`, and what's the one you usually want.
