### ISSUE TITLE
Documentation typo: "Style.Arrowheads"

### ISSUE THREAD

**Issue by elliotdickison** [BohemianCoding/SketchAPI#546]
The [documentation for Style.Arrowheads](https://github.com/BohemianCoding/SketchAPI/blob/develop/docs/api/Style.md#stylearrowheads) should be `Style.Arrowhead` (singular), according to what actually works in code for me (Sketch 55.1 / 78136).

Btw loving the new JS API, hadn't done Sketch development in a couple years and it's sooo much better now! Thanks for the great work on that.

**Comment by mathieudutour** [comment]
Ah yes good catch!

**Comment by mathieudutour** [comment]
fixed here: https://github.com/BohemianCoding/SketchAPI/commit/de4030ed1b8246abdf30e35096ca1453069c2524
