### ISSUE TITLE
remote libraries

### ISSUE THREAD

**Issue by DrinkingWords** [BohemianCoding/SketchAPI#555]
There are two remote libraries with different symbols. They have the same names and different paths. So I use their paths to distinguish them as following.

```
let libraries = sketch.getLibraries().filter(l => {
      let path = l.valid && l.enabled && l.getDocument() && l.getDocument().path;
      return l.valid && l.enabled && l.libraryType === 'Remote' && path = path; 
});
```

And I get the symbols that can be imported by:

```
libraries[0].getImportableSymbolReferencesForDocument(document ); 
```

But I get the same quantity of symbols with the two different libraries. In fact there are 288 symbols in one library and 315 symbols in the other. Is there something wrong in my code?

**Comment by mathieudutour** [comment]
I'm not sure I understand what you are trying to do. Why do you assign `path` to `path` in your conditional?

**Comment by jedrichards** [comment]
Is it just a typo in your `filter` function?

```
return l.valid && l.enabled && l.libraryType === 'Remote' && path = path;
                                                                  ^
                                                          This looks strange
```

**Comment by DrinkingWords** [comment]
It is a typo here. It should be:
return l.valid && l.enabled && l.libraryType === 'Remote' && path === path;
Path is appcast URL.
The problems still exist.

**Comment by mathieudutour** [comment]
It’s still weird, path will always be equal to itself. What are you trying to do?

**Comment by DrinkingWords** [comment]
I add a romote library by Library.getRemoteLibraryWithRSS('https://url/to/1/rss.xml', () => {}). Then I add another remote library by Library.getRemoteLibraryWithRSS('https://url/to/2/rss.xml', () => {}). The two libraries have a same name and different paths. One path is 'https://url/to/1/res.sketch' and the other is 'https://url/to/2/res.sketch'.  So I can distinguish them by their paths. I mean if I want to get the library first added, I will get it's path and see if it equals to 'https://url/to/1/res.sketch'. 
let libraries = sketch.getLibraries().filter(l => {
      let path = l.valid && l.enabled && l.getDocument() && l.getDocument().path;
      return l.valid && l.enabled && l.libraryType === 'Remote' && path == 'https://url/to/1/res.sketch'; 
});
After I get the library which path is 'https://url/to/1/res.sketch', I get the symbols that can be imported by libraries[0].getImportableSymbolReferencesForDocument(document ); 
But I get the symbols in the other library which path is 'https://url/to/2/res.sketch'.
Did I make everything clear？I am so sorry for my poor English and thank you for your  patience.
