### ISSUE TITLE
Instances of `SharedStyle` and `ColorAsset` not recognizing library update

### ISSUE THREAD

**Issue by jwdallas** [BohemianCoding/SketchAPI#556]
I have a Sketch plugin that programmatically updates a Sketch library with new names/values for `sharedLayerStyles` and `colors`. This works great except that when the library updates instances of those library assets are not updated.

What seems to be happening is that Sketch isn't marking `sharedLayerStyles` or `colors` as having been updated if the Sketch API modified it. Possibly because there is no GUI in the Sketch app that allows this?

I saw mention of a `changeIdentifier` property [here](https://github.com/seek-oss/html-sketchapp-cli/issues/18) however I'm not sure exactly how to use that since it doesn't seem to be included in the docs.

**Comment by jwdallas** [comment]
Actually, thinking about this more, the problem is probably that I'm recreating all of the `sharedLayerStyles` and `colors` in Sketch Library each time the plugin runs. I’m carefully preserving the name / value of these and just taking the changes. However because i'm blowing away the document’s arrays and totally replacing them with new items each time, it looks like the `id` for each item is getting totally replaced which I suppose makes it look like a brand new thing instead of what I was expecting which was update to the previously existed thing.

This behavior makes sense now, I wish I'd realize it earlier, but c'est la vie.

**Comment by mathieudutour** [comment]
Indeed, you need to preserve the IDs so that Sketch knows they are the same objects 👍

**Comment by mathieudutour** [comment]
Indeed, you need to preserve the IDs so that Sketch knows they are the same objects 👍

**Comment by mathieudutour** [comment]
Indeed, you need to preserve the IDs so that Sketch knows they are the same objects 👍
