### ISSUE TITLE
Create reference files for Sketch 56

### ISSUE THREAD

**Issue by christianklotz** [BohemianCoding/SketchAPI#583]
There's been Sketch 56, 56.1 and 56.2 with the point releases really being patch releases only so it may be sufficient to just provide a general update for 56.

**Comment by jedrichards** [comment]
Yep good thinking. Maybe take this opportunity to re-organise the files so that the generator plugin is local to the versions, rather than being global?

**Comment by christianklotz** [comment]
Sounds good
