### ISSUE TITLE
Why isn't this more known?

### ISSUE THREAD

**Issue by bensmeets** [BohemianCoding/SketchAPI#6]
What am I missing here. Just happened to drop in here and it looks awesome. Is it me or is this gem a little hidden currently?

**Comment by samdeane** [comment]
It's work-in-progress :)

Version 40 (released today!) includes a more up to date version of this API, but it's still far from complete. 

We are actively developing it though, and it will get better over time.

**Comment by samdeane** [comment]
The whole idea of the API, when it's done, is that plugin developers should be able to rely on it not changing.

Since it's currently changing a lot, I'm not keen to promote it too widely until things have calmed down!

**Comment by BenjaminCorey** [comment]
@samdeane Any reason why the most recent version isn't reflected in this repository? It would be nice to reference the production API when building plugins against the production app.

**Comment by kgn** [comment]
I just stumbled onto this project too, it's great! Can't wait to see where it goes and would love to help contribute to get it there. Is there a roadmap that could be shared so people looking to contribute could know what would be good to tackle/implement? To know what functions are desired that haven't been implemented in order to implement them and submit pull requests.

**Comment by bomberstudios** [comment]
We don't yet have a public roadmap, but I agree that's a good thing to have : )

Will discuss with the team and see what's the best way to approach that, in terms of tools (feedback is definitely welcome!)

**Comment by tim-dose-zocdoc** [comment]
This is really cool stuff! Excited to see where it goes.

**Comment by samdeane** [comment]
You are right that I should make a roadmap :)

I should say though that I'm quite keen to keep this API as lean-and-mean as I can. The main reason for that is that if we (Bohemian) are committing ourselves to making sure that we don't break it, then it's essential that doing so doesn't become an unmanageable task.

I'm thinking of this API as a very *core* layer which interfaces with Sketch itself. Even with the small amount that I've done so far, I can definitely see the temptation to broaden the API and add lots of convenience methods and/or higher-level code that builds on the API. I think that's something that we should do as a community, but it makes sense to try to keep it separate from the core API effort.

**Comment by samdeane** [comment]
> I just stumbled onto this project too, it's great! Can't wait to see where it goes and would love to help contribute to get it there. Is there a roadmap that could be shared so people looking to contribute could know what would be good to tackle/implement? To know what functions are desired that haven't been implemented in order to implement them and submit pull requests.

I'm thinking of this API as a very core layer which interfaces with Sketch itself. Even with the small amount that I've done so far, I can definitely see the temptation to broaden the API and add lots of convenience methods and/or higher-level code that builds on the API. I think that's something that we should do as a community, but it makes sense to try to keep it separate from the core API effort.

**Comment by samdeane** [comment]
None of which means that I want to discourage participation, just that we've got to be careful.

One thing I've been contemplating is a more layered approach, like this:

![api layers](https://cloud.githubusercontent.com/assets/206306/19645098/f7d3615c-99ea-11e6-962a-439fb553bf2d.png)

There's no reason why we couldn't maintain two libraries, and have the utilities one *only* work with calls to the *api* one. That could have a lot more community input, and as long as it just calls the API, it should stay stable (if the API does!).

**Comment by plrthink** [comment]
@samdeane Agree with this approach. I think we(community) can't do development well about this repo(Sketch API) since the app(Sketch) itself is a blackbox for us. The Sketch API should be maintained by the people who build the Sketch.

**Comment by bomberstudios** [comment]
Will copy that diagram to the README and close this issue (with a sad heart, since the discussion is pretty interesting) if that's ok with you.

**Comment by samdeane** [comment]
Sounds like a plan. That diagram was just a suggestion though, and I don't want to make promises we can't keep (about anything!).

**Comment by mathieudutour** [comment]
I'll close this as this is not really actionable :)
