### ISSUE TITLE
Evolve developer website deployment process

### ISSUE THREAD

**Issue by jedrichards** [BohemianCoding/SketchAPI#607]
As far as we can tell the current process looks something like:

- Developer website build process is housed in the SketchAPI repo (this may change soon, but it's how it is for now)
- Netlify is used for deploy previews in PRs
- The https://developer.sketch.com site is hosted on GitHub Pages, and deployments are made manually by invoking the `deploy.sh`script to merge the current branch into the `gh-pages` branch

In order to converge on one host (Netlify) and make the deployment process align with other web properties like the marketing site, we need to make some changes:

- [x] Add a protected `master` branch to the SketchAPI repo (ensure that this is initially branched off the most recent `release/XX` branch that represents a version of Sketch released to the wild)
- [x] Ensure that the `developer-sketch` Netlify site auto-publishes `master` to https://developer-sketch.netlify.com
- [x] Update https://developer.sketch.com DNS to point to https://developer-sketch.netlify.com

In the future, when we want to re-deploy the developer website we can setup a PR from `release/XX+n` to `master` again.

**Comment by jelledelaender** [comment]
Should be all done - waiting until DNS is propagated fully :) 

We can remove GH pages next week.

**Comment by christianklotz** [comment]
Thank you @jelledelaender 🙇 

@jedrichards to finish the job next week:

- [ ] remove `gh-pages` branch and whatever else is left over from GitHub pages
- [ ] update `README`
- [ ] remove redundant deploy scripts
- [ ] remove redundant `package.json` script entries
- [ ] document release process internally
