### ISSUE TITLE
Artboard object has no export method

### ISSUE THREAD

**Issue by oxyberg** [BohemianCoding/SketchAPI#77]
Hello! So on, I have been working on my plugin for a while, and I have experienced the issue with exporting artboards.

I have an array of duplicated artboards:
```js
var tmpArtboards = [];
rootLayers.forEach(function(rootLayer) {
    var tmp = rootLayer.duplicate();
    // ...
    tmpArtboards.push(tmp);
});
```

I try to set the export options for the artboards:
```js
var options = {'scales': '1', 'formats': 'png'};
tmpArtboards.forEach(function(artboard) {
    artboard.export(options);
});
```
I get this:
```
TypeError: artboard.export is not a function. (In 'artboard.export(options)', 'artboard.export' is undefined)
```
As I know, **Artboard** inherits **Layer** and I should be able to use `export` method, but it seems that these objects are not belong to **Layer**.

**Comment by mathieudutour** [comment]
yes I believe `duplicate` was returning `WrappedObject` instead of an object of the same type. This will be fixed with new API. (and `export` will be a top-level method that accept an array directly)

**Comment by oxyberg** [comment]
May be where's a roadmap for the new API release?

**Comment by mathieudutour** [comment]
hopefully it will ship with Sketch 49. We will talk more about it soon
