### ISSUE TITLE
how to "detach from symbol" in code way?

### ISSUE THREAD

**Issue by ziven27** [BohemianCoding/SketchAPI#81]
I can detach a symbol on right click dropdown list.
Is there any way to do this in code way?

**Comment by mathieudutour** [comment]
#78 is going to make this easy.

For now, if you have a symbol instance, you can use `instance.detachByReplacingWithGroup()`

**Comment by ziven27** [comment]
thx ,that is help me a lot.
where can I find this kind of api ?
I just can find the new api on the home page of http://developer.sketchapp.com/

**Comment by mathieudutour** [comment]
that's the internal API of Sketch, it's not documented because there are thousands of methods and they are changing when we work on Sketch, eg, everyday.

You can read more here: http://developer.sketchapp.com/reference/

**Comment by ziven27** [comment]
ok, thx for your help again.
I can get a MS objetct with  instance._object，
How can i get a  sketch object with a MS instance ?

**Comment by colorgmi** [comment]
In Sketch53Beta, it seems does not have the `detachByReplacingWithGroup` method.
