### ISSUE TITLE
feature: prevent change of getSelectionFromUser values

### ISSUE THREAD

**Issue by DanielRuf** [BohemianCoding/SketchAPI#87]
So far it seems the input values can be changed by users which should be prevented.
How can we prevent that they change the available options?

**Comment by mathieudutour** [comment]
I'm not sure what you mean, you want the user to be able to change the value since the methods are made for getting a value from the user

**Comment by DanielRuf** [comment]
No, the current problem is that when you give them options using `getSelectionFromUser` and `getStringFromUser` that the options in the UI are editable.

**Comment by mathieudutour** [comment]
ah good catch for the `getSelectionFromUser`, it will be fixed in Sketch 49.

I'm not sure about the `getStringFromUser`, there is no option, you only specify the default value. If you don't want the user to change it, what's the point of using that method?

**Comment by DanielRuf** [comment]
> Currently my trial has expired so I might have to check if I can get a license for further testing and development.

That's why I also had not much time to test the `fetch` polyfill so far. Might have to install the trial on my other MacBook.

**Comment by mathieudutour** [comment]
Cool, I'll close this then as it will be fixed in the new version
