### ISSUE TITLE
How to find a symbol master by name?

### ISSUE THREAD

**Issue by szimek** [BohemianCoding/SketchAPI#99]
I'm trying to write a plugin that will set overrides in symbol instances in specific layer groups based on data from a JSON file.

The first problem is that overrides in a symbol instance don't have any name or label, it looks like I can only reference them by index in overrides array. I figured out that maybe I could get these names from the symbol master. However, I can't figure out how to get an existing symbol master. The API only mentions how to create one, not how to find one.

**Comment by nichenqin** [comment]
It looks like the name property can be accessed via `String(this._object.overridePoint().layerName())` but the `Override` class did not implement the method.

[https://github.com/abynim/Sketch-Headers/blob/4a95b06c0d5e620249f40583e25d3dc52e36494b/Headers/MSOverridePoint.h#L21](url)

**Comment by mathieudutour** [comment]
You can find a symbol master using `document.findSymbolMaster()`: http://developer.sketchapp.com/reference/api/#find-a-symbol-master.

Be careful when dealing with names because they are not unique.
